\input texinfo
@include version.texi
@setfilename guide.info
@settitle Programming in Star

@dircategory Programming
@direntry
* star-guide: (star).		Programming in Star
@end direntry

@copying
Copyright @copyright{} 2019 and beyond, Francis G. McCabe

All rights reserved.
@end copying

@titlepage
@title Programming in Star
@author Francis G. McCabe

@page
@insertcopying
@end titlepage

@ifplaintext
@insertcopying
@end ifplaintext

@summarycontents
@contents

@include macros.texi

@node Top
@top Star Guide

@noindent
This is the 
@ifinfo
on-line
@end ifinfo 
guide for the @Star{} language.  
@refill

@noindent
This book gives an introduction into the form and usage of the @Star{}
programming language. However, it is not a definitive reference on the
language; for which the reader is referred to @xref{Top,,,star,The
Star Reference} by F.G. McCabe.

@menu
* Why be a Star programmer?::
* A tour of Star::
* Functional Programming::
* Collections::
* Making choices::
* Boiling the Ocean::

* Are We Done Yet::

* Concept index::
* Function index::
* List of Syntax Rules::
@end menu

@include intro.texi

@include tour.texi

@include func.texi

@include collections.texi

@include rules.texi

@include ocean.texi

@c @include monads.texi

@c @include concurrency.texi

@c @include policy.texi

@c @include market.texi

@include arewedone.texi


@node Concept index
@unnumbered Concept index
@printindex cp

@node Function index
@unnumbered Standard function index
@printindex fn

@node List of Syntax Rules
@unnumbered List of Syntax Rules
@listoffloats BNF


@bye
