= Representing Policy

One of the design goals for Star was that it would be able to stretch from
relatively low-level problems to very high-level ones. In particular, we should
be able to borrow some of the powerful features of languages like Prolog and SQL
to express high-level concepts.

In this chapter we look at how the combination of query expressions and set data
structures -- together with the more normal features of the language -- can be
combined to construct an effective policy mechanism.

== Application = Mechanism + Policy

It is an informal truism of software engineering that it is often easier to
solve a more general version of a presented problem and to then allow
customization of that solution for particular needs. This is also how we can
amortize the cost of development across multiple use-cases.

We can crystalize this idea by factoring applications into two parts: a
mechanism that embodies the functionality of the application and a policy that
guides us how to actually use the mechanism.

We see this from two perspectives: that of the owner of the application and that
of the application code itself.

=== What is a policy?

One reasonable definition of policy is in terms of constraints:

Policy:: a constraint on the behavior of a system. This includes
constraints on people interacting with the system as well as constraints on the
elements of the system itself.

For example, we might have a policy of never lending books to library customers
if they have any outstanding fines. Any lending software should honor this
constraint when a reader tries to check out a book.

Yet another take on the question looks at it from the point of view of
the application:

Policy:: is the answer to a question that code has that cannot be directly
answered within the application or from its input.

Taking the lending example for example, somewhere in the code there will be a
function that allows a user to check out a book (and assign the book to their
currently checked out list). The same code will typically have a condition along
the lines of:

[source,star]
----
checkoutBook(User,Book) => valof {
  if lendingIsPermitted(Book,User) then{
    assignBook(Book,User);
    valis .checkout(User,Book)
  } else {
    logMsg(.warning,"User $(User) not allowed to borrow $(Book)");
    valis .denied
  }
}
----

Functions such ``lendingIsPermitted`` are not typically hard coded into lending
applications, nor is the answer to the question included in the input data (the
user's name and the book they want to check out).footnote:[Although the user
might have presented additional input -- such as a special pass -- that the
application can use to override its own reluctance.]

In this way of conceptualizing policies and policy enforcement is that the
overall system contains an _oracle_ whose role is to answer policy _questions_
that the application(s) have.

Both views on policies are valid, and can help us design an effective means of
governing systems.

== A policy language

A key differentiator of different policy systems is the expressiveness
of the notation that one can use to represent policies.

In this chapter we take an approach that models polices in terms of _sets_ of
atomic fragments and _queries_ over them for particular scenarios. In
particular, we will leverage the RDF capabilities that we support: we shall use
RDF triples to denote policies and SPARQL queries to query the policy database.




=== Atomic Policies


Configuration of software is often expressed in terms of key/value
pairs. For example, the Star compiler has a configuration point of
where the code repository lives. This is expressed as the value
associated with the key `star-repo` and its value should be a
directory.

[sidebar]
====
It is a separate question of how configuration information information
is delivered to the software. In the case of a command line tool like
a compiler this is often realized by so-called command line options.

Other systems, again typically services that are expected to be long
running, read their configuration from files.

For our purposes, how the system gets the information is not relevant.
====

The repository directory is an example of an _atomic_ policy: an
indivisible fact that represents a constraint on the system.

Another example of an atomic policy might be the maximum balance a
reader may have before being permitted to borrow a library book.

We can model such atomic policies by using type definitions:


[source,star]
----
compilerConfig ::= repoDir(directory).

readerFinancialConfig ::= maximumBalance(money).
----


A typical system has many such atomic policies; of different kinds and
relating to different areas. Our library might also be concerned with
the number of servers deployed at any one time -- such a policy should
not be mixed with the concerns of readers:


[source,star]
----
deployment ::= concurrentServers(integer)
           | standardPort(integer)
           | databaseUrl(uri).
----


Some atomic polices have more than one parameter. For example, our
library system may need to know how much to fine a reader for a late
return. That in turn depends on the number of days that it is late:


[source,star]
----
fineSchedule ::= lateness{days:integer. fine:money}. -- days 
----

where there might be a set of such thresholds:

[source,star]
----
[lateness{days=3. fine=pennies(225)},
  lateness{days=10. fine=pennies(500)},
  lateness{days=14. fine=dollars(25)}]:set[fineSchedule]
----


[sidebar]
====
The notation

[source,star]
----
[ El1, .., Eln] : set[Type]
----

is one way in which we can denote a `set` value in Star.
====

== Querying Policies

Programs respond to policies by asking the `policy oracle' at
appropriate moments. This is often deep in the heart of the
application; however, the process is simple enough: ask the oracle.

Questions in Star are often expressed as _queries_; for example, in the function:


[source,star]
----
mayBorrow(Reader,Book) =>
  accountBalance(Reader) < maximumBalance.
----


except that `maximumBalance` should not be hard-coded; instead we
ask what that is:


[source,star]
----
mayBorrow(Reader,Book) where {? maximumBalance(Max) in oracle ?} =>
  accountBalanace(Reader) < Max.
----


The condition

[source,star]
----
{? maximumBalance(Max) in oracle ?}
----

is a simple query that is satisfied if the `oracle` has a record
of the `maximumBalance` permitted.

NOTE:
If the oracle does not have that information then the query
_fails_ and an alternate must be found; maybe the library will
lend the book if it does not have a policy about reader balances:


[source,star]
----
mayBorrow(Reader,Book) default => true.
----

