= Why be a Star programmer?

This book is about the programming language called Star. Why, you
may ask, do you need to learn yet another language? We hope to answer
that question and more in the course of this book. We also aim to show
you how to program effectively in Star to solve real world
problems.

== Is Star for you?

Choosing a programming language -- when you actually have a choice --
is highly personal. Here are some reasons to think about Star.

=== If you are already a Java (or C#) Programmer

Most OO languages are embracing some of the simpler features of
functional languages. Even modern Java with its lambda expressions and
stream features represents a nod to the power of functional
programming. However, at the same time, there is a substantial gap in
the capabilities of most OO languages compared to modern functional
programming languages.

Fundamentally, OO languages revolve around _nouns_ rather than
_verbs_. Verbs (methods) are relegated to being inside the scope
of some noun (object): they are not first class.  In functional
programming languages, like Star, there is more of an balance
between nouns and verbs.

It is possible to have functions that are about data; it is also quite
straightforward in functional programming languages to have data
structures with functions embedded in them. In fact, a simple
definition of a _module_ is a record that contains functions in
it.

While OO languages like Java provide excellent _data abstraction_
tools, the same cannot be said for _control abstractions_. The
result is that OO languages are '`stuck` in the 1970s' when it comes to
control abstractions. However, concepts such as map/reduce,
computation expressions, and continuations bring a rich suite of new
control possibilities that solve important problems in modern
programming.

Similarly, the type systems of languages like Java (or C# or C/C++)
make are not as expressive or sensitive as modern type systems in
functional languages can be. Professional programmers will recognize a
typical symptom of insufficiently expressive types: lots of casting
and dynamic meta-programming. But, while powerful, these techniques
amount to giving up on types and their important
advantages. Furthermore, contrary to many programmers' expectations, a
modern type system is quite capable of dealing statically with
scenarios that require dynamic programming in languages like Java.

=== If you are already a Python programmer

The biggest difference between a language like Star and Python is the strict
type system. All Star programs are strictly type checked. In addition, there is
no escape from the type system: you cannot pretend that a variable has the right
type: it either does or it doesnt.

That said, this could be viewed as an advantage to the serious Python
programmer: all those type errors that you have to run your Python program to
find out will be discovered by the compiler. Indeed, it is quite common that,
once Star programs pass the compiler's type checking system, they 'just
work™'.footnote:[Star is not speical here, it is true of many programming
languages with similarly strict type systems.]

Some of the reasons that proponents of dynamically typed languages quote as
benefits are conciseness (no need to tell the compiler what the programmer
already knows) and flexibility (the programmer can do what they want, without
persuading the type system that they know what they are doing).

These justifications used to have some merit -- and still do wrt languages like
Java. However, modern type systems are quite powerful and enable the programmer
to express quite subtle requirements. Star's type system is based on the concept
of _constrained types_; and is able to express programming paradigms such as
having records with generic functions in them, or to express the idea of a
function that throws an exception, but the type of the exception is itself
dependent on other types.

In addition, Star uses _type inference_ to avoid the need to explicit type
annotations. Type inference is able to eliminate nearly all the boilerplate
needed to declare variables and functions. Star does require some type
declarations; but these are constrained to areas that legitimately merit
documentation: for example, when a function is intended to be universally
generic, then you need to say that explicitly. Similarly, when installing a
generic function in a data structure -- or passing it as an argument to a
function -- then, there too, the programmer needs to be explicit.

=== If you are already a C++ programmer

Moving to a language like Star is a radically different programming
experience for the C++ programmer. However, most of the differences
are not because Star is a functional programming language. Rather,
it is because Star does not abide by two of C's core principles:
zero-cost abstractions and compatibility with C.

While Star's compiler does not willfully make programs execute more
slowly, strict CPU performance is not the primary driver for design
features. This shows up in a desire to avoid the so-called premature
optimization problem: of optimizing the wrong feature.

In the case of Star vs C++, the most salient of these is likely to
be the different ways that generic programs are compiled: C++ compiles
generic programs by constructing special case implementations for all
used versions of the generic program; whereas Star constructs a
single -- type agnostic -- implementation of generic functions.

This affects many aspects of one's day-to-day usage of the language
and its tooling. One of which is that, for a compiler that has been in
daily use for over 40 years, C++ compilers are still remarkably
slow. C++ binaries can often be very large -- typically outclassed in
performance by the Java compiler.

The compatibility with C requirement has meant that C++ has to support
many programming paradigms (such as pointer arithmetic) that most
modern programming languages -- Star included -- eschew.

Pointer arithmetic is known to put applications at risk of severe
security problems; and there are many modern safer alternatives (which
C++ does also support).

Beyond these, you will find Star to be a rich and expressive
language; especilly if your focus is on applications rather than
systems programming.

=== If you are already a functional programmer

You have many choices for functional programming languages that are
excellent. The author considers two languages that are principal
sources of inspiration for many of the functional features of Star:
Haskell and Standard ML (SML) -- both of which are excellent; but not
perfect.

For the functional programmer, the principal benefits of Star are
_readability_, _modernity_ and _predictability_.

One of the major drivers of the design of Haskell and (to a lesser
extent) SML is conciseness. However, conciseness is not the same as
readability. In modern software development environments there are
many stakeholders beyond the developer. Having a language that is easy
to follow by non-technical readers is a major benefit in mixed skill
teams.

Like Haskell, Star has a powerful type system. Star's type
system has many features in common with Haskell's type system --
features that typically go beyond the capabilities of many OO
languages. In particular, Star's contract system is reminiscent of
Haskell's type classes; and Star's existential and higher-kinded
types give considerable expressive power to the programmer.

Star does not follow all of Haskell's type features; and some type
concepts are rephrased into terminology that is more familiar to
main-stream (sic) programmers.

Like SML, Star has a powerful module system. However, unlike SML's
functors, Star modules are first class values. This means that
there is no artificial separation between '`ordinary`' programs and
'`functor`' programs.

The result is a balanced set of type features that provides
capabilities that scale well from small programs to large systems.

Star's evaluation is, like that of SML but unlike Haskell,
strict. We believe that that makes it significantly easier to reason
about the actual behavior and performance of programs. However,
Star has a rich set of features that support productive concurrent
and parallel programming.

Like SML, Star is not a strictly '`pure`' language. This was neither
an accident nor an afterthought. Computer systems are built to fulfill
purposeful activity (although there may be many times when the actual
purpose is hard to discern). For example, if I deposit a check into my
bank account, I require that the bank's state is updated to reflect my
new balance: the world has changed as a result of my action.

However, the converse does not follow: just because the world is
stateful does not mean that all our programs should be needlessly
stateful. Much, if not most, of a given application program can and
should be crafted in a mathematical style -- the merits of functional
programming are very great.

Overall, the primary rationale in the design of Star is to empower
the programmer in making obviously correct programs.

== Design goals for Star

Star is a multi-paradigm high-level _symbolic_ language. It is
designed to be scalable, readable, accurate, high performing and
extensible.

Paradoxically, scalability in a programming language is always about
large and small chunks of code. Scalability in Star is fostered by
a range of elements that facilitate composition, change and re-use.

=== Type System

Star is a strongly, statically typed language. The purpose of a
strong type system is to facilitate the communication of intent of the
programmer. The purpose of static typing is to ensure that the
compiler can rapidly '`fail`' incorrect programs without requiring the
program to be run. Furthermore, static type checking minimizes any
run-time penalty for imposing type constraints.

Although Star is strongly typed, it uses _type inference_ to
eliminate much of the clutter that some type systems impose on the
programmer -- which itself is a productivity sink of course.

Generally, the _stronger_ the type system, the more the language
system can detect errors before programs are run. In addition, the
more _expressive_ the type system is, the less the temptation to
try to subvert or bypass the type system.

However, even though it is technically feasible to completely
eliminate type declarations of functions; doing so is in conflict with
some of the other goals behind Star. For example, type declarations
act as a form of documentation; and when there is a type error in your
program, having _no_ explicit type declarations can make tracking
the culprit of the error very difficult. So all top-level variable
definitions (typically functions) are required in Star to have
explicit type _annotations_.footnote:[The term _type
declaration_ is reserved for defining a new type. Variable types are
defined through _type annotations_.]

[NOTE]
****
Some features are missing from Star's type system -- by design:

* There is no notion of subtyping, and by extension, no equivalent of an `any`
  type. In effect, the type system does _not_ have any escape hatch into the
  untyped world.
+
  Originally, this was an experiment: to see if it was
  possible. However, today, the author is convinced that subtypes and both
  unnecessary and confusing.
* There is no equivalent of the type cast that one sees in languages like C, C++
  and Java.
* There is no automatic conversion of values from one type to another. For
  example, there is no automatic conversion of integer values to floating point
  values. The reasons for this include the fact that such automatic conversions
  can be difficult to spot in the source code, and can lead to errors that are
  hard to uncover.
****

=== Readability

The syntax of Star is oriented towards readability rather than
strict conciseness. The reason for this is that the programmer is only
one of the stake holders in a given program. A readable program is one
that is more easily trusted by non-programmers.

Experience also suggests that readability enhances programmer
productivity also: much of team-based development involves
comprehending and modifying other programmers' code.

Readability is not just about using words instead of symbols. It is about making
choices in the language that enhance the reader's ability to determine what the
program is about.

Two examples might illustrate our point:

* Enumerated symbols and data constructor values are distinguished from
  variables and function calls with a syntactic marker -- a leading period. This
  includes the symbols for `.true` and `.false`!
  +
  The reason for this is that
  variables are very powerful in Star and without some form of syntactic marker
  it becomes too easy for the programmer to make mistakes that may not be
  obvious.

* So-called generic types -- types with quantified variables -- must have their
  quantifiers explicitly written. For example, a function type that returns its
  argument (the so-called identity function) has a type written as:
+
[source,star]
----
id:all x ~~ (x)=>x.
----
+
  The reason for this, apart from the additional clarity, is that Star allows
generic functions to be 'stored' in structures and passed as arguments to
functions. In such cases, it becomes imperative to be able to properly identify the scope of type vairables.

=== Interface Oriented vs Object Oriented

Star is not an object-oriented language: there is no concept of class, instance
or sub-class. However, some of the aspects of OO languages are too valuable to
discard. In particular, the concept of interface is very important, especially
in larger programs.

The most direct analog of _interface_ in Star is the _contract_. A contract is a
declaration of a set of functionality that is related -- but which can be
separately specified from implementation.

Star's use of contracts is more-or-less pervasive in the language. So much so
that many of Star's own features are grounded in contracts. This together with
the ease of providing implementations is one of the more powerful features.

For example, Star has a notation for expressing sequences of elements; such as:
[source,star]
----
["alpha", "beta", "gamma"]
----
Rather than 'wasting' this notation on a particular representation type, the
sequence notation is grounded in two contracts: `stream` and `sequence`. This
allows the sequence notation to be used on a wide variety of types of
collections.

== About this book

This book acts as an introduction to the language and to its use. The
basic features of the language are introduced; however, this is not a
reference manual: it is not intended to be a complete description of
the language.

That can be found in the Star Language Definition.

Introducing a programming language like Star can be a challenge in
presentation. This is because there is a significant amount of mutual
support between elements of the language.

Our strategy is to take a layered approach -- we start with simple
examples, occasionally skipping over certain aspects of the language
without explanation. Later chapters focus on deeper, more complex
topics.

For the most part, examples in the text of the book are
executable. You are encouraged to try to get them running on your own
system.

=== Getting hold of Star
The Star compiler and run-time is being developed as an open source
project on GitHub. You can access the source by cloning or downloading
the repository at

[source, text]
----
github.com/fgmccabe/star
----

=== Typographical conventions

Any text on a programming language often has a significant number of
examples of programs and program fragments. We show these using a
typewriter-like font, often broken out in a display form:

[source, star]
----
P:integer;
----

NOTE: As we noted above, Star is a rich language with many features. As a
result, some parts of the text may require more careful reading, or
represent comments about potential implications of the main
text. These notes are highlighted the way this note is.

=== Acknowledgements

No-one is an island, and no project of this scale is one person's
work. I have had the great fortune to be able to develop Star in
the context of real world applications solving hard
problems. Individuals have also played a large role; and it can be
hard to ensure that all are properly acknowledged: please forgive any
omissions.

Of particular significance, I would like to thank Michael Sperber for
our many discussions on the finer topics of language design; and for
his not insignificant contributions to the early implementation effort.

I would also like to thank my old colleagues at Starview inc., in particular
Steve Baunach and Bob Riemenschneider who were the world's first Star
programmers! In addition, I would like to thank David Frese and Andreas Bernauer
who helped with crucial parts of the implementation of the early versions of the
concurrency. I would also like to thank Keith Clark, Kevin Cory, Prasenjit Dey,
Chris Gray, Mack Mackenzie, and Kevin Twidle for their help and advice. I would
like to acknowledge the support of Thomas Sulzbacher who originated the project
and Jerry Meerkatz for keeping the faith.

Last, but definitely not least, I would like to acknowledge the love
and support of my family; without whom none of this makes sense.
