/* 
 * Access the opcodes of the Star machine
 * (c) 2013, 2018, 2024, 2026 and beyond F.G.McCabe
 * all rights reserved
 **/

#ifndef SSA_OPCODES_H_
#define SSA_OPCODES_H_

typedef enum {
    sHalt = 0,
    sAbort = 1,
    sCall = 2,
    sOCall = 3,
    sEscape = 4,
    sTCall = 5,
    sTOCall = 6,
    sRSP = 7,
    sRSX = 8,
    sEntry = 9,
    sRtn = 10,
    sRet = 11,
    sXRet = 12,
    sBlock = 13,
    sBreak = 14,
    sResult = 15,
    sCont = 16,
    sICase = 17,
    sCase = 18,
    sIxCase = 19,
    sCLbl = 20,
    sCInt = 21,
    sCChar = 22,
    sCFlt = 23,
    sCLit = 24,
    sMC = 25,
    sMv = 26,
    sLG = 27,
    sSG = 28,
    sSav = 29,
    sLdSav = 30,
    sTstSav = 31,
    sStSav = 32,
    sCell = 33,
    sGet = 34,
    sAssign = 35,
    sNth = 36,
    sStNth = 37,
    sIAdd = 38,
    sISub = 39,
    sIMul = 40,
    sIDiv = 41,
    sIMod = 42,
    sIAbs = 43,
    sIEq = 44,
    sILt = 45,
    sIGe = 46,
    sCEq = 47,
    sCLt = 48,
    sCGe = 49,
    sBAnd = 50,
    sBOr = 51,
    sBXor = 52,
    sBLsl = 53,
    sBLsr = 54,
    sBAsr = 55,
    sBNot = 56,
    sFAdd = 57,
    sFSub = 58,
    sFMul = 59,
    sFDiv = 60,
    sFMod = 61,
    sFAbs = 62,
    sFEq = 63,
    sFLt = 64,
    sFGe = 65,
    sAlloc = 66,
    sClosure = 67,
    sFiber = 68,
    sSuspend = 69,
    sResume = 70,
    sRetire = 71,
    sUnderflow = 72,
    sLine = 73,
    sBind = 74,
    sdBug = 75,

  sInval,
  maxCode = sInval
} ssaOp;

static char *ssaOpNames[] = {
      "Halt",
      "Abort",
      "Call",
      "OCall",
      "Escape",
      "TCall",
      "TOCall",
      "RSP",
      "RSX",
      "Entry",
      "Rtn",
      "Ret",
      "XRet",
      "Block",
      "Break",
      "Result",
      "Cont",
      "ICase",
      "Case",
      "IxCase",
      "CLbl",
      "CInt",
      "CChar",
      "CFlt",
      "CLit",
      "MC",
      "Mv",
      "LG",
      "SG",
      "Sav",
      "LdSav",
      "TstSav",
      "StSav",
      "Cell",
      "Get",
      "Assign",
      "Nth",
      "StNth",
      "IAdd",
      "ISub",
      "IMul",
      "IDiv",
      "IMod",
      "IAbs",
      "IEq",
      "ILt",
      "IGe",
      "CEq",
      "CLt",
      "CGe",
      "BAnd",
      "BOr",
      "BXor",
      "BLsl",
      "BLsr",
      "BAsr",
      "BNot",
      "FAdd",
      "FSub",
      "FMul",
      "FDiv",
      "FMod",
      "FAbs",
      "FEq",
      "FLt",
      "FGe",
      "Alloc",
      "Closure",
      "Fiber",
      "Suspend",
      "Resume",
      "Retire",
      "Underflow",
      "Line",
      "Bind",
      "dBug"};

#ifndef OPCODE_SIGNATURE
#define OPCODE_SIGNATURE 2096417289399390681
#endif

typedef enum {
  Slcl = 'v',
  Slcls = 'V',
  SoUt = 'o',
  SoUts = 'O',
  SpHi = 'p',
  SpHis = 'P',
  Slcm = 'm',
  Slit = 'l',
  Sglb = 'g',
  Sart = 'a',
  Si32 = 'i',
  SEs = 'e',
  SbLk = 'k',
  SlVl = 'b',
  Ssym = 's'
} argSpecType;

#endif // SSA_OPCODES_H
