/* 
 * Access the opcodes of the Star machine
 * (c) 2013, 2018, 2024, 2026 and beyond F.G.McCabe
 * all rights reserved
 **/

#ifndef SSA_OPCODES_H_
#define SSA_OPCODES_H_

typedef enum {
    sHalt = 0,
    sAbort = 1,
    sCall = 2,
    sOCall = 3,
    sEscape = 4,
    sTCall = 5,
    sTOCall = 6,
    sRSP = 7,
    sRSX = 8,
    sEntry = 9,
    sRtn = 10,
    sRet = 11,
    sXRet = 12,
    sBlock = 13,
    sValof = 14,
    sBreak = 15,
    sResult = 16,
    sLoop = 17,
    sIf = 18,
    sIfNot = 19,
    sICase = 20,
    sCase = 21,
    sIxCase = 22,
    sCLbl = 23,
    sCInt = 24,
    sCChar = 25,
    sCFlt = 26,
    sCLit = 27,
    sMC = 28,
    sMv = 29,
    sLG = 30,
    sSG = 31,
    sSav = 32,
    sLdSav = 33,
    sTstSav = 34,
    sStSav = 35,
    sCell = 36,
    sGet = 37,
    sAssign = 38,
    sNth = 39,
    sStNth = 40,
    sIAdd = 41,
    sISub = 42,
    sIMul = 43,
    sIDiv = 44,
    sIMod = 45,
    sIAbs = 46,
    sIEq = 47,
    sILt = 48,
    sIGe = 49,
    sCEq = 50,
    sCLt = 51,
    sCGe = 52,
    sBAnd = 53,
    sBOr = 54,
    sBXor = 55,
    sBLsl = 56,
    sBLsr = 57,
    sBAsr = 58,
    sBNot = 59,
    sFAdd = 60,
    sFSub = 61,
    sFMul = 62,
    sFDiv = 63,
    sFMod = 64,
    sFAbs = 65,
    sFEq = 66,
    sFLt = 67,
    sFGe = 68,
    sAlloc = 69,
    sClosure = 70,
    sBump = 71,
    sDrop = 72,
    sFiber = 73,
    sSuspend = 74,
    sResume = 75,
    sRetire = 76,
    sUnderflow = 77,
    sLine = 78,
    sBind = 79,
    sdBug = 80,

  sInval,
  maxCode = sInval
} ssaOp;

static char *ssaOpNames[] = {
      "Halt",
      "Abort",
      "Call",
      "OCall",
      "Escape",
      "TCall",
      "TOCall",
      "RSP",
      "RSX",
      "Entry",
      "Rtn",
      "Ret",
      "XRet",
      "Block",
      "Valof",
      "Break",
      "Result",
      "Loop",
      "If",
      "IfNot",
      "ICase",
      "Case",
      "IxCase",
      "CLbl",
      "CInt",
      "CChar",
      "CFlt",
      "CLit",
      "MC",
      "Mv",
      "LG",
      "SG",
      "Sav",
      "LdSav",
      "TstSav",
      "StSav",
      "Cell",
      "Get",
      "Assign",
      "Nth",
      "StNth",
      "IAdd",
      "ISub",
      "IMul",
      "IDiv",
      "IMod",
      "IAbs",
      "IEq",
      "ILt",
      "IGe",
      "CEq",
      "CLt",
      "CGe",
      "BAnd",
      "BOr",
      "BXor",
      "BLsl",
      "BLsr",
      "BAsr",
      "BNot",
      "FAdd",
      "FSub",
      "FMul",
      "FDiv",
      "FMod",
      "FAbs",
      "FEq",
      "FLt",
      "FGe",
      "Alloc",
      "Closure",
      "Bump",
      "Drop",
      "Fiber",
      "Suspend",
      "Resume",
      "Retire",
      "Underflow",
      "Line",
      "Bind",
      "dBug"};

#ifndef OPCODE_SIGNATURE
#define OPCODE_SIGNATURE 672621438903973766
#endif

typedef enum {
  Slcl = 'v',
  Slcls = 'V',
  Slcm = 'm',
  Slit = 'l',
  Sglb = 'g',
  Sart = 'a',
  Si32 = 'i',
  SEs = 'e',
  SbLk = 'k',
  SlVl = 'b',
  Ssym = 's'
} argSpecType;

#endif // SSA_OPCODES_H
