/* 
 * Access the opcodes of the Star machine
 * (c) 2013, 2018, 2024, 2026 and beyond F.G.McCabe
 * all rights reserved
 **/

#ifndef SSA_OPCODES_H_
#define SSA_OPCODES_H_

typedef enum {
    Halt = 0,
    Abort = 1,
    Call = 2,
    OCall = 3,
    Escape = 4,
    XCall = 5,
    XOCall = 6,
    XEscape = 7,
    TCall = 8,
    TOCall = 9,
    Entry = 10,
    Ret = 11,
    Rtn = 12,
    XRet = 13,
    Block = 14,
    Valof = 15,
    Break = 16,
    Result = 17,
    Loop = 18,
    If = 19,
    IfNot = 20,
    CLbl = 21,
    CInt = 22,
    CChar = 23,
    CFlt = 24,
    CLit = 25,
    ICase = 26,
    Case = 27,
    IxCase = 28,
    MvV = 29,
    MvC = 30,
    Mv = 31,
    MvR = 32,
    MvG = 33,
    StG = 34,
    Sav = 35,
    LdSav = 36,
    TstSav = 37,
    StSav = 38,
    Cell = 39,
    Get = 40,
    Assign = 41,
    Nth = 42,
    StNth = 43,
    IAdd = 44,
    ISub = 45,
    IMul = 46,
    IDiv = 47,
    IMod = 48,
    IAbs = 49,
    IEq = 50,
    ILt = 51,
    IGe = 52,
    CEq = 53,
    CLt = 54,
    CGe = 55,
    BAnd = 56,
    BOr = 57,
    BXor = 58,
    BLsl = 59,
    BLsr = 60,
    BAsr = 61,
    BNot = 62,
    FAdd = 63,
    FSub = 64,
    FMul = 65,
    FDiv = 66,
    FMod = 67,
    FAbs = 68,
    FEq = 69,
    FLt = 70,
    FGe = 71,
    Alloc = 72,
    Closure = 73,
    Fiber = 74,
    Suspend = 75,
    Resume = 76,
    Retire = 77,
    Underflow = 78,
    Line = 79,
    Bind = 80,
    dBug = 81,

  sInval,
  maxCode = sInval
} ssaOp;

static char *ssaOpNames[] = {
      "Halt",
      "Abort",
      "Call",
      "OCall",
      "Escape",
      "XCall",
      "XOCall",
      "XEscape",
      "TCall",
      "TOCall",
      "Entry",
      "Ret",
      "Rtn",
      "XRet",
      "Block",
      "Valof",
      "Break",
      "Result",
      "Loop",
      "If",
      "IfNot",
      "CLbl",
      "CInt",
      "CChar",
      "CFlt",
      "CLit",
      "ICase",
      "Case",
      "IxCase",
      "MvV",
      "MvC",
      "Mv",
      "MvR",
      "MvG",
      "StG",
      "Sav",
      "LdSav",
      "TstSav",
      "StSav",
      "Cell",
      "Get",
      "Assign",
      "Nth",
      "StNth",
      "IAdd",
      "ISub",
      "IMul",
      "IDiv",
      "IMod",
      "IAbs",
      "IEq",
      "ILt",
      "IGe",
      "CEq",
      "CLt",
      "CGe",
      "BAnd",
      "BOr",
      "BXor",
      "BLsl",
      "BLsr",
      "BAsr",
      "BNot",
      "FAdd",
      "FSub",
      "FMul",
      "FDiv",
      "FMod",
      "FAbs",
      "FEq",
      "FLt",
      "FGe",
      "Alloc",
      "Closure",
      "Fiber",
      "Suspend",
      "Resume",
      "Retire",
      "Underflow",
      "Line",
      "Bind",
      "dBug"};

#ifndef OPCODE_SIGNATURE
#define OPCODE_SIGNATURE 1856896583037917357
#endif

typedef enum {
  Slcl = 'v',
  Slcls = 'V',
  Slit = 'l',
  Sglb = 'g',
  Sart = 'a',
  Si32 = 'i',
  SEs = 'e',
  SbLk = 'k',
  SlVl = 'b',
  Ssym = 's'
} argSpecType;

#endif // SSA_OPCODES_H
