
[#austin:60]: John L. Austin, "_How to do things with words_", Oxford : Clarendon, 1962

[#Reppy1999]: John H. Reppy, "_Concurrent Programming in ML_", Cambridge University Press, 1999

[#Bagwell01idealhash]: Phil Bagwell, "_Ideal Hash Trees_". in Es Grands Champs, Vol. 1195, 2001

[#FIPA]: "_The Foundation of Intelligent Physical Agents_" <http://www.fipa.org/index.html>

[#hoare78]: C. A. R. Hoare, "_Communicating Sequential Processes_". in Communications of the ACM, Vol. 21, 8 666-677, 1978

[#hoare85]: C. A. R. Hoare, "_Communicating Sequential Processes_", Prentice Hall, 1985

[#kqml:93]: T. Finin.  et al. "_DRAFT specification of the KQML Agent Communication Language_". The DARPA knowledge sharing initiative External Interfaces Working Group. 1993

[#rfc2396]: Tim Berners Lee. "_RFC2396: Uniform Resource Identifiers (URI): Generic Syntax_" 1998. <https://www.ietf.org/rfc/rfc2396.txt>

[#N3-W3C]: Tim Berners Lee.  and Dan Connolly. "_Notation3 (N3): A readable RDF syntax_" 2011. <http://www.w3.org/TeamSubmission/n3/>

[#searle:69]: J. R. Searle, "_Speech acts: an essay in the philosophy of language_", Cambridge University Press, 1969

