Title: Programming in Star
Author: Francis G, McCabe

{{intro.mmd}}

{{tour.mmd}}

{{func.mmd}}

{{collections.mmd}}

{{rules.mmd}}

{{ocean.mmd}}

{{monads.mmd}}

{{concurrency.mmd}}

{{policy.mmd}}

{{market.mmd}}

{{arewedone.mmd}}

{{appendix.mmd}}

{{bibliography.mmd}}


