# Are We Done Yet?[are-we-done-yet]

This book takes you on a journey starting with very simple **Star** programs and ending with a platform that is capable of being deployed on large scale distributed networks. In the meantime we also explored some quite deep topics in functional programming, concurrency and developing domain specific languages.

The truth is, of course, that we are only able to scratch the surface of many of the topics we cover. So, the question is what next?

If you want to go deeper into **Star** itself then the natural source is the language definition -- which can be obtained at [Github](https://github.com/fmccabe/Star/releases/download/v101RC1/reference.pdf). This covers the language and its standard library.

If you want to go deeper in concurrency then there are several sources one may go to. However, we recommend Reppy's [][#Reppy1999] original book on Concurrent ML. Our only complaint about this book is that it is not based on **Star**!

There is much material on agent programming of various flavors. A good place to start is also [Wikipedia](http://en.wikipedia.org/wiki/Agent-oriented_programming). For a variety of reasons we also recommend investigating the different specifications produced by the Foundation of Physical Intelligent Agents [FIPA](http://www.fipa.org).

Finally, dear reader, I would like to thank you for staying the course. I would like to recommend that you check out **Star** with your own programs and please keep us informed of your adventures by writing: <fmccabe@gmail.com>.
