#line 2 "/home/fgm/cafe/src/Asm/asmToken.c"

#line 4 "/home/fgm/cafe/src/Asm/asmToken.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
#define yy_create_buffer ss_create_buffer
#define yy_delete_buffer ss_delete_buffer
#define yy_flex_debug ss_flex_debug
#define yy_init_buffer ss_init_buffer
#define yy_flush_buffer ss_flush_buffer
#define yy_load_buffer_state ss_load_buffer_state
#define yy_switch_to_buffer ss_switch_to_buffer
#define yyin ssin
#define yyleng ssleng
#define yylex sslex
#define yylineno sslineno
#define yyout ssout
#define yyrestart ssrestart
#define yytext sstext
#define yywrap sswrap
#define yyalloc ssalloc
#define yyrealloc ssrealloc
#define yyfree ssfree

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ssrestart(ssin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int ssleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *ssin, *ssout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE sslex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-sslineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < ssleng; ++yyl )\
                    if ( sstext[yyl] == '\n' )\
                        --sslineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --sslineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up sstext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up sstext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ssrestart()), so that the user can continue scanning by
	 * just pointing ssin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when sstext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int ssleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow sswrap()'s to do buffer switches
 * instead of setting up a fresh ssin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void ssrestart (FILE *input_file  );
void ss_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ss_create_buffer (FILE *file,int size  );
void ss_delete_buffer (YY_BUFFER_STATE b  );
void ss_flush_buffer (YY_BUFFER_STATE b  );
void sspush_buffer_state (YY_BUFFER_STATE new_buffer  );
void sspop_buffer_state (void );

static void ssensure_buffer_stack (void );
static void ss_load_buffer_state (void );
static void ss_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ss_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ss_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ss_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ss_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *ssalloc (yy_size_t  );
void *ssrealloc (void *,yy_size_t  );
void ssfree (void *  );

#define yy_new_buffer ss_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ssensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ss_create_buffer(ssin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ssensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ss_create_buffer(ssin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] sstext/ssin/ssout/yy_state_type/sslineno etc. def's & init go here */
/* Begin user sect3 */

#define sswrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *ssin = NULL, *ssout = NULL;

typedef int yy_state_type;

extern int sslineno;

int sslineno = 1;

extern char *sstext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr sstext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up sstext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle sstext and ssleng for yymore() goes here \ */\
	ssleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to sstext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[186] =
    {   0,
        0,    0,    6,    6,    0,    0,    0,    0,   76,   75,
        2,    1,   62,   42,   48,   49,   75,   43,   46,   44,
       41,   38,   39,    9,   48,   48,   48,   48,   48,   48,
       48,   48,   10,   48,   48,   48,   48,   11,    6,    5,
        7,   74,   64,   63,   75,   61,   51,   50,   75,    2,
       48,    0,   48,    0,   44,    4,    0,   46,   47,    0,
        0,   44,   40,   48,   23,   22,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   29,   48,   48,   48,
       48,   48,   48,   48,   48,   30,   48,    6,    7,    7,
        8,   74,   73,   65,   73,   66,   73,   67,   68,   69,

       70,   71,   72,   61,   60,   52,   60,   53,   60,   54,
       55,   56,   57,   58,   59,    0,   44,   47,    0,   47,
       45,   48,   48,   48,   21,   48,   25,   34,   48,   48,
       48,   48,   19,   48,   48,   48,   48,   48,   48,   18,
       27,   28,   48,   65,    0,   66,    0,   52,    0,   53,
        0,    0,    3,   48,   13,   20,   24,   48,   48,   12,
       48,   48,   48,   48,   48,   48,   26,   16,   65,   52,
       31,   48,   32,   48,   33,   14,   17,   48,   48,   15,
       37,   48,   36,   35,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    7,    1,
        1,    8,    9,    1,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   15,   15,   16,   17,    1,
        1,    1,    1,    6,   18,   18,   18,   18,   19,   18,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,   20,    6,    6,
       21,   22,   23,    1,    6,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,    6,   40,   41,   42,   43,    6,    6,   20,
        6,    6,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[44] =
    {   0,
        1,    1,    2,    3,    4,    4,    5,    6,    1,    1,
        4,    1,    7,    7,    7,    1,    8,    7,    7,    4,
        1,    3,    1,    7,    7,    7,    7,    7,    7,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4
    } ;

static yyconst flex_uint16_t yy_base[201] =
    {   0,
        0,    0,   41,   42,   43,   48,   50,   52,  360,  361,
      357,  361,  361,    0,    0,  351,   48,  349,   64,   74,
      340,  361,  361,  320,   19,   40,   26,   30,  314,  329,
      316,  315,   53,   55,   58,   58,  308,  325,    0,  361,
       82,    0,  361,  361,   90,    0,  361,  361,  120,  346,
        0,  340,  361,  344,  107,  361,  110,  139,  150,  161,
        0,  166,  361,  310,    0,    0,   65,  305,  305,  303,
      314,  314,  315,  303,  298,  297,    0,  309,  310,  309,
      306,  101,  289,  288,  287,    0,  296,    0,  143,  160,
      361,    0,  361,  169,  310,  361,   51,  309,  308,  307,

      361,  361,  361,    0,  361,  174,  306,  361,  167,  305,
      304,  303,  361,  361,  361,  316,  182,  185,  188,  192,
        0,  280,  282,  270,    0,  254,    0,    0,  267,  254,
      240,  237,    0,  250,  231,  230,  224,  212,  211,    0,
        0,    0,  183,  195,  194,  361,  193,  203,  176,  361,
      197,  189,  361,  164,    0,    0,    0,  134,  138,    0,
      119,  121,  108,  106,  116,   99,    0,    0,  112,  111,
        0,   85,    0,   69,    0,    0,    0,   80,   72,    0,
        0,   67,    0,    0,  361,  220,  228,  236,  241,  248,
      256,  264,  272,  280,  288,  296,   53,  298,  300,  308

    } ;

static yyconst flex_int16_t yy_def[201] =
    {   0,
      185,    1,  186,  186,  187,  187,  188,  188,  185,  185,
      185,  185,  185,  189,  189,  190,  185,  185,  185,  185,
      185,  185,  185,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  191,  185,
      192,  193,  185,  185,  194,  195,  185,  185,  196,  185,
      189,  190,  185,  185,  185,  185,  185,  185,  185,  185,
      197,  185,  185,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  191,  192,  192,
      185,  193,  185,  198,  198,  185,  198,  198,  198,  198,

      185,  185,  185,  195,  185,  199,  199,  185,  199,  199,
      199,  199,  185,  185,  185,  200,  185,  185,  185,  185,
      197,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  198,  198,  185,  198,  199,  199,  185,
      199,  200,  185,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  198,  199,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,    0,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185

    } ;

static yyconst flex_uint16_t yy_nxt[405] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   10,   10,   17,
       15,   18,   19,   20,   20,   21,   10,   15,   15,   15,
       22,   10,   23,   24,   25,   26,   27,   28,   29,   15,
       30,   31,   32,   15,   33,   15,   15,   34,   35,   36,
       37,   38,   15,   40,   40,   43,   44,   65,   41,   41,
       43,   44,   47,   10,   47,   10,   48,   54,   48,  121,
       66,   55,   55,   67,   45,   69,   71,  146,   70,   45,
       72,   49,  147,   49,   57,   68,   58,   58,   59,   77,
       79,   81,   60,   61,   57,   83,   62,   62,   62,   90,
       78,   60,   60,   91,  184,   84,   80,  183,   85,  123,

       82,   60,   94,   94,   95,  124,   96,   95,   95,  182,
      181,   97,  180,   98,   99,   95,   95,   95,  100,  117,
      117,  117,  118,  118,  118,  138,  101,  150,  146,  102,
      179,  103,  106,  106,  107,  139,  108,  107,  107,  178,
      177,  109,  176,  110,  111,  107,  107,  107,  112,   57,
      185,   58,   58,   59,  185,  175,  113,   60,  174,  114,
       57,  115,   59,   59,   59,  173,   60,   90,   60,  119,
      119,   91,  172,  120,  120,  120,   57,   60,   62,   62,
       62,  144,  144,  150,   60,  146,  148,  148,  151,  171,
      150,  153,  150,   60,  117,  117,  117,  118,  118,  118,

      120,  120,  120,   60,  120,  120,  120,  169,  169,  146,
      146,  146,   60,  150,  147,  170,  170,  168,  151,  150,
       39,   39,   39,   39,   39,   39,   39,   39,   42,   42,
       42,   42,   42,   42,   42,   42,   46,   46,   46,   46,
       46,   46,   46,   46,   51,  167,  166,   51,   52,   52,
       52,   52,   52,   52,   52,   52,   88,  165,   88,   88,
       88,  164,   88,   88,   89,  163,   89,   89,   89,   89,
       89,   89,   92,  162,  161,   92,   92,   92,   92,   92,
       93,  160,   93,   93,   93,   93,   93,   93,  104,  159,
      158,  104,  157,  104,  104,  104,  105,  156,  105,  105,

      105,  105,  105,  105,  145,  145,  149,  149,  152,  152,
      152,  152,  152,  152,  152,  152,  155,  154,  153,  150,
      150,  150,  150,  146,  146,  146,  146,  143,  142,  141,
      140,  137,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  122,  116,   53,   50,   87,   86,
       76,   75,   74,   73,   64,   63,   56,   53,   50,  185,
        9,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,

      185,  185,  185,  185
    } ;

static yyconst flex_int16_t yy_chk[405] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    5,   25,    3,    4,
        6,    6,    7,    7,    8,    8,    7,   17,    8,  197,
       25,   17,   17,   26,    5,   27,   28,   97,   27,    6,
       28,    7,   97,    8,   19,   26,   19,   19,   19,   33,
       34,   35,   19,   19,   20,   36,   20,   20,   20,   41,
       33,   19,   20,   41,  182,   36,   34,  179,   36,   67,

       35,   20,   45,   45,   45,   67,   45,   45,   45,  178,
      174,   45,  172,   45,   45,   45,   45,   45,   45,   55,
       55,   55,   57,   57,   57,   82,   45,  170,  169,   45,
      166,   45,   49,   49,   49,   82,   49,   49,   49,  165,
      164,   49,  163,   49,   49,   49,   49,   49,   49,   58,
       89,   58,   58,   58,   89,  162,   49,   58,  161,   49,
       59,   49,   59,   59,   59,  159,   58,   90,   59,   60,
       60,   90,  158,   60,   60,   60,   62,   59,   62,   62,
       62,   94,   94,  109,   62,   94,  106,  106,  109,  154,
      106,  152,  149,   62,  117,  117,  117,  118,  118,  118,

      119,  119,  119,  118,  120,  120,  120,  144,  144,  147,
      145,  144,  118,  151,  147,  148,  148,  143,  151,  148,
      186,  186,  186,  186,  186,  186,  186,  186,  187,  187,
      187,  187,  187,  187,  187,  187,  188,  188,  188,  188,
      188,  188,  188,  188,  189,  139,  138,  189,  190,  190,
      190,  190,  190,  190,  190,  190,  191,  137,  191,  191,
      191,  136,  191,  191,  192,  135,  192,  192,  192,  192,
      192,  192,  193,  134,  132,  193,  193,  193,  193,  193,
      194,  131,  194,  194,  194,  194,  194,  194,  195,  130,
      129,  195,  126,  195,  195,  195,  196,  124,  196,  196,

      196,  196,  196,  196,  198,  198,  199,  199,  200,  200,
      200,  200,  200,  200,  200,  200,  123,  122,  116,  112,
      111,  110,  107,  100,   99,   98,   95,   87,   85,   84,
       83,   81,   80,   79,   78,   76,   75,   74,   73,   72,
       71,   70,   69,   68,   64,   54,   52,   50,   38,   37,
       32,   31,   30,   29,   24,   21,   18,   16,   11,    9,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,

      185,  185,  185,  185
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[76] =
    {   0,
1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ss_flex_debug;
int ss_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[75] =
    {   0,
       86,   88,   90,   92,   93,   94,   95,   96,   98,   99,
      100,  102,  104,  105,  106,  107,  108,  110,  111,  112,
      114,  115,  116,  118,  119,  120,  121,  122,  124,  125,
      127,  129,  130,  131,  133,  134,  135,  137,  138,  139,
      140,  141,  142,  144,  149,  151,  153,  157,  182,  185,
      192,  193,  197,  201,  202,  203,  204,  205,  206,  207,
      208,  215,  218,  225,  227,  231,  235,  236,  237,  238,
      239,  240,  241,  242
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *sstext;
#line 1 "asmToken.l"
/* Lexical scanner for the Cafe assembler */



#line 16 "asmToken.l"
#include <config.h>
#include <ooio.h>

#include <math.h>
#include <unistr.h>
#include <assemP.h>
#include <assem.h>
#include <code.h>
#include <term.h>

#include <assem.h>

#include "assem.h"

#include "asmGrammar.h"

#define MAX_STR_CONST 2048

#define YY_DECL int sslex(union SSSTYPE *yylval_param, SSLTYPE *yylloc_param, ioPo yyFile_param)
extern int sslex(union SSSTYPE *yylval_param, SSLTYPE *yylloc_param, ioPo ssFile);

static ioPo ssFile;

#define YY_USER_INIT ssFile = yyFile_param;

#define YY_INPUT(buf,result,max) {\
    integer act;\
    retCode ret = inBytes(ssFile,(unsigned char*)buf,max,&act);	\
    if(ret==Eof)\
      result = YY_NULL;				\
    else\
      result = act;				\
  }

#define YY_NO_INPUT

#define YYLTYPE SSLTYPE
#define YYSTYPE SSSTYPE

static void parseError(char *msg,int lineNo);
static long octtoi(char *text);
static long hextoi(char *text);

#define RT(K) { yylloc->first_line = yylloc->last_line = sslineno; return K;}

static long parseLong(char *text)
{
  return parseInteger(text,strlen(text));
}

static double parseFloat(char *text)
{
  return parseNumber(text,strlen(text));
}

#line 809 "/home/fgm/cafe/src/Asm/asmToken.c"

#define INITIAL 0
#define comment 1
#define string 2
#define quoted 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int sslex_destroy (void );

int ssget_debug (void );

void ssset_debug (int debug_flag  );

YY_EXTRA_TYPE ssget_extra (void );

void ssset_extra (YY_EXTRA_TYPE user_defined  );

FILE *ssget_in (void );

void ssset_in  (FILE * _in_str  );

FILE *ssget_out (void );

void ssset_out  (FILE * _out_str  );

			int ssget_leng (void );

char *ssget_text (void );

int ssget_lineno (void );

void ssset_lineno (int _line_number  );

/* %if-bison-bridge */

YYSTYPE * ssget_lval (void );

void ssset_lval (YYSTYPE * yylval_param  );

       YYLTYPE *ssget_lloc (void );
    
        void ssset_lloc (YYLTYPE * yylloc_param  );
    
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int sswrap (void );
#else
extern int sswrap (void );
#endif
#endif

/* %not-for-header */

#ifndef YY_NO_UNPUT
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( sstext, (size_t) ssleng, 1, ssout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ssin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ssin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, ssin))==0 && ferror(ssin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ssin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int sslex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int sslex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after sstext and ssleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ssin )
/* %if-c-only */
			ssin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! ssout )
/* %if-c-only */
			ssout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			ssensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ss_create_buffer(ssin,YY_BUF_SIZE );
		}

		ss_load_buffer_state( );
		}

	{
/* %% [7.0] user's declarations go here */
#line 84 "asmToken.l"


#line 1117 "/home/fgm/cafe/src/Asm/asmToken.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of sstext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 186 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 361 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for sslineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < ssleng; ++yyl )
				if ( sstext[yyl] == '\n' )
					
    sslineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( ss_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 75 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], sstext );
			else if ( yy_act == 75 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         sstext );
			else if ( yy_act == 76 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 86 "asmToken.l"
RT(NL);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 88 "asmToken.l"
/* ignore */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 90 "asmToken.l"
RT(NL);			/* line comment */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "asmToken.l"
BEGIN(comment);
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 93 "asmToken.l"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "asmToken.l"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 95 "asmToken.l"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 96 "asmToken.l"
BEGIN(INITIAL);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "asmToken.l"
RT(A);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "asmToken.l"
RT(L);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "asmToken.l"
RT(T);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "asmToken.l"
RT(HALT);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "asmToken.l"
RT(CALL);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 105 "asmToken.l"
RT(OCALL);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "asmToken.l"
RT(ESCAPE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 107 "asmToken.l"
RT(TAIL);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 108 "asmToken.l"
RT(OTAIL);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 110 "asmToken.l"
RT(RET);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 111 "asmToken.l"
RT(JMP);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 112 "asmToken.l"
RT(CASE);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 114 "asmToken.l"
RT(CMP);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 115 "asmToken.l"
RT(BT);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 116 "asmToken.l"
RT(BF);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 118 "asmToken.l"
RT(DROP)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 119 "asmToken.l"
RT(DUP)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 120 "asmToken.l"
RT(PULL)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 121 "asmToken.l"
RT(ROT)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 122 "asmToken.l"
RT(RST)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "asmToken.l"
RT(LD);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "asmToken.l"
RT(ST);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 127 "asmToken.l"
RT(ALLOC);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 129 "asmToken.l"
RT(FRAME);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 130 "asmToken.l"
RT(LOCAL);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 131 "asmToken.l"
RT(END);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 133 "asmToken.l"
RT(PKG);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 134 "asmToken.l"
RT(PUBLIC);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 135 "asmToken.l"
RT(IMPORT);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 137 "asmToken.l"
RT(LBRA);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 138 "asmToken.l"
RT(RBRA);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 139 "asmToken.l"
RT(DCOLON);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 140 "asmToken.l"
RT(COLON);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 141 "asmToken.l"
RT(HASH);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 142 "asmToken.l"
RT(SLASH);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 144 "asmToken.l"
{
  yylval->i = parseLong(sstext);
  RT(DECIMAL);
		   }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 149 "asmToken.l"
{ yylval->i = hextoi(sstext); RT(DECIMAL); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 151 "asmToken.l"
{ yylval->i = octtoi(sstext); RT(DECIMAL); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 153 "asmToken.l"
{
  yylval->f = parseFloat(sstext); RT(FLOAT);
	       }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 157 "asmToken.l"
{ yylval->str = uniDuplicate(sstext); RT(ID); }
	YY_BREAK

  char buff[MAX_STR_CONST];
  char *text = &buff[0];
  long size = NumberOf(buff);
  long pos = 0;

#define putChar(ch) {				\
    if(pos>=size){				\
      char *nBuff = (char*)malloc((size+size/2)*sizeof(char));\
      for(int ix=0;ix<pos;ix++)\
	nBuff[ix]=text[ix];    \
      if(text!=buff)	       \
	free(text);	       \
      text = nBuff;	       \
    }			       \
    text[pos++] = (ch);	       \
	      }

#define restart() { text = &buff[0]; pos=0; size=NumberOf(buff); }
#define clear() { if(text!=buff){ free(text); restart(); } }

case 49:
YY_RULE_SETUP
#line 182 "asmToken.l"
{ restart(); BEGIN(quoted); }
	YY_BREAK

case 50:
YY_RULE_SETUP
#line 185 "asmToken.l"
{
    BEGIN(INITIAL);
    putChar('\0');
    yylval->str = uniDuplicate(text);
    clear();
    RT(ID);
  }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 192 "asmToken.l"
{ parseError("unterminated quoted name",sslineno); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 193 "asmToken.l"
{
    int octCode = octtoi(sstext);
    putChar(octCode);
  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 197 "asmToken.l"
{
    long hexCode = hextoi(sstext);
    putChar(hexCode);
  }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 201 "asmToken.l"
putChar('\a');
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 202 "asmToken.l"
putChar('\b');
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 203 "asmToken.l"
putChar('\f');
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 204 "asmToken.l"
putChar('\n');
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 205 "asmToken.l"
putChar('\r');
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 206 "asmToken.l"
putChar('\t');
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 207 "asmToken.l"
putChar(sstext[1]);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 208 "asmToken.l"
{
    char *yptr = sstext;
    while(*yptr)
      putChar(*yptr++);
  }
	YY_BREAK

case 62:
YY_RULE_SETUP
#line 215 "asmToken.l"
{ restart(); BEGIN(string); }
	YY_BREAK

case 63:
YY_RULE_SETUP
#line 218 "asmToken.l"
{
    BEGIN(INITIAL);
    putChar('\0');
    yylval->str = uniDuplicate(text);
    clear();
    RT(STRING);
  }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 225 "asmToken.l"
{ parseError("unterminated string",sslineno);
  }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 227 "asmToken.l"
{
    int octCode = octtoi(sstext);
    putChar(octCode);
  }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 231 "asmToken.l"
{
    long hexCode = hextoi(sstext);
    putChar(hexCode);
  }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 235 "asmToken.l"
putChar('\a');
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 236 "asmToken.l"
putChar('\b');
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 237 "asmToken.l"
putChar('\f');
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 238 "asmToken.l"
putChar('\n');
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 239 "asmToken.l"
putChar('\r');
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 240 "asmToken.l"
putChar('\t');
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 241 "asmToken.l"
putChar(sstext[1]);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 242 "asmToken.l"
{
    char *yptr = sstext;
    while(*yptr)
      putChar(*yptr++);
  }
	YY_BREAK

case 75:
YY_RULE_SETUP
#line 249 "asmToken.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1651 "/home/fgm/cafe/src/Asm/asmToken.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(string):
case YY_STATE_EOF(quoted):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ssin at a new source and called
			 * sslex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ssin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( sswrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * sstext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of sslex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ssrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ssrestart(ssin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ssrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 186 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 186 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 185);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ssrestart(ssin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( sswrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve sstext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and sslineno */
	if ( c == '\n' )
		
    sslineno++;
;

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void ssrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ssensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ss_create_buffer(ssin,YY_BUF_SIZE );
	}

	ss_init_buffer(YY_CURRENT_BUFFER,input_file );
	ss_load_buffer_state( );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void ss_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		sspop_buffer_state();
	 *		sspush_buffer_state(new_buffer);
     */
	ssensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ss_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (sswrap()) processing, but the only time this flag
	 * is looked at is after sswrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void ss_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	ssin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE ss_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ssalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ss_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ssalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ss_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ss_init_buffer(b,file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with ss_create_buffer()
 * 
 */
/* %if-c-only */
    void ss_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ssfree((void *) b->yy_ch_buf  );

	ssfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ssrestart() or at EOF.
 */
/* %if-c-only */
    static void ss_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	ss_flush_buffer(b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ss_init_buffer was _probably_
     * called from ssrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void ss_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ss_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void sspush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	ssensure_buffer_stack();

	/* This block is copied from ss_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ss_switch_to_buffer. */
	ss_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void sspop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ss_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ss_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void ssensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)ssalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ssensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ssrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ssensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ss_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) ssalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ss_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ss_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to sslex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ss_scan_bytes() instead.
 */
YY_BUFFER_STATE ss_scan_string (yyconst char * yystr )
{
    
	return ss_scan_bytes(yystr,(int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to sslex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ss_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) ssalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ss_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ss_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ss_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up sstext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		sstext[ssleng] = (yy_hold_char); \
		(yy_c_buf_p) = sstext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ssleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int ssget_lineno  (void)
{
    
    return sslineno;
}

/** Get the input stream.
 * 
 */
FILE *ssget_in  (void)
{
        return ssin;
}

/** Get the output stream.
 * 
 */
FILE *ssget_out  (void)
{
        return ssout;
}

/** Get the length of the current token.
 * 
 */
int ssget_leng  (void)
{
        return ssleng;
}

/** Get the current token.
 * 
 */

char *ssget_text  (void)
{
        return sstext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void ssset_lineno (int  _line_number )
{
    
    sslineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see ss_switch_to_buffer
 */
void ssset_in (FILE *  _in_str )
{
        ssin = _in_str ;
}

void ssset_out (FILE *  _out_str )
{
        ssout = _out_str ;
}

int ssget_debug  (void)
{
        return ss_flex_debug;
}

void ssset_debug (int  _bdebug )
{
        ss_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from sslex_destroy(), so don't allocate here.
     */

    /* We do not touch sslineno unless the option is enabled. */
    sslineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ssin = stdin;
    ssout = stdout;
#else
    ssin = NULL;
    ssout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * sslex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* sslex_destroy is for both reentrant and non-reentrant scanners. */
int sslex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ss_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		sspop_buffer_state();
	}

	/* Destroy the stack itself. */
	ssfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * sslex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ssalloc (yy_size_t  size )
{
			return malloc(size);
}

void *ssrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void ssfree (void * ptr )
{
			free( (char *) ptr );	/* see ssrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 249 "asmToken.l"



static void parseError(char *msg, int lineno)
{
  outMsg(logFile,"problem %s with token at %U/%l",msg,fileName(ssFile),lineno);
}

static int octValue(char ch)
{
  return ch-'0';
}

static long octtoi(char *text)
{
  long val = 0;
  char *octStr = text;
  while(*octStr!='\0'){
    int Oct = octValue(*octStr++);

    if(0<=Oct && Oct<8)
      val = val*8+Oct;
    else
      outMsg(logFile,"octal number %s not valid at %U/%l",text,fileName(ssFile),sslineno);
  }
  return val;
}

static int hexValue(char ch)
{
  return ch-'0';
}

static long hextoi(char *text)
{
  long val = 0;

  if(strncmp(text,"0x",2)==0){
    char *hexStr = text+strlen("0x");

    while(*hexStr!='\0'){
      int Hex = hexValue(*hexStr++);

      if(0<=Hex && Hex<16)
	val = val*16+Hex;
      else
	outMsg(logFile,"hex number %s not valid at %U/%l",text,fileName(ssFile),sslineno);
    }
  }
  else if(strncmp(text,"+",1)==0){
    char *hexStr = text+1;
    while(*hexStr!='\0' && *hexStr!=';'){
      int Hex = hexValue(*hexStr++);

      if(0<=Hex && Hex<16)
	val = val*16+Hex;
      else
	outMsg(logFile,"hex number %s not valid at %U/%l",text,fileName(ssFile),sslineno);
    }
  }
  else
    outMsg(logFile,"hex number %s not valid at %U/%l",text,fileName(ssFile),sslineno);

  return val;
}

