/* Automatically generated, do not edit */

:-module(escapes,[isEscape/1,escapeType/2]).

escapeType("_exit",funType([type("star.core*integer")],voidType)).
escapeType("_command_line",funType([],typeExp(tpFun("star.core*list",1),[type("star.core*string")]))).
escapeType("_command_opts",funType([],typeExp(tpFun("star.core*list",1),[tupleType([type("star.core*string"),type("star.core*string")])]))).
escapeType("_identical",univType(kVar("t"),funType([kVar("t"),kVar("t")],type("star.core*logical")))).
escapeType("_defined",funType([type("star.core*string"),type("star.core*integer")],type("star.core*logical"))).
escapeType("_int_plus",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_int_minus",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_int_times",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_int_div",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_int_mod",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_flt_plus",funType([type("star.core*float"),type("star.core*float")],type("star.core*float"))).
escapeType("_flt_minus",funType([type("star.core*float"),type("star.core*float")],type("star.core*float"))).
escapeType("_flt_times",funType([type("star.core*float"),type("star.core*float")],type("star.core*float"))).
escapeType("_flt_div",funType([type("star.core*float"),type("star.core*float")],type("star.core*float"))).
escapeType("_flt_mod",funType([type("star.core*float"),type("star.core*float")],type("star.core*float"))).
escapeType("_int_abs",funType([type("star.core*integer")],type("star.core*integer"))).
escapeType("_flt_abs",funType([type("star.core*integer")],type("star.core*integer"))).
escapeType("_int_eq",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*logical"))).
escapeType("_int_lt",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*logical"))).
escapeType("_int_ge",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*logical"))).
escapeType("_flt_eq",funType([type("star.core*float"),type("star.core*float")],type("star.core*logical"))).
escapeType("_flt_lt",funType([type("star.core*float"),type("star.core*float")],type("star.core*logical"))).
escapeType("_flt_ge",funType([type("star.core*float"),type("star.core*float")],type("star.core*logical"))).
escapeType("_int2flt",funType([type("star.core*integer")],type("star.core*float"))).
escapeType("_flt2int",funType([type("star.core*float")],type("star.core*integer"))).
escapeType("_flt_hash",funType([type("star.core*float")],type("star.core*integer"))).
escapeType("_pwr",funType([type("star.core*float"),type("star.core*float")],type("star.core*float"))).
escapeType("sqrt",funType([type("star.core*float")],type("star.core*float"))).
escapeType("exp",funType([type("star.core*float")],type("star.core*float"))).
escapeType("log",funType([type("star.core*float")],type("star.core*float"))).
escapeType("log10",funType([type("star.core*float")],type("star.core*float"))).
escapeType("pi",funType([],type("star.core*float"))).
escapeType("sin",funType([type("star.core*float")],type("star.core*float"))).
escapeType("cos",funType([type("star.core*float")],type("star.core*float"))).
escapeType("tan",funType([type("star.core*float")],type("star.core*float"))).
escapeType("asin",funType([type("star.core*float")],type("star.core*float"))).
escapeType("acos",funType([type("star.core*float")],type("star.core*float"))).
escapeType("atan",funType([type("star.core*float")],type("star.core*float"))).
escapeType("trunc",funType([type("star.core*float")],type("star.core*float"))).
escapeType("floor",funType([type("star.core*float")],type("star.core*float"))).
escapeType("ceil",funType([type("star.core*float")],type("star.core*float"))).
escapeType("integral",funType([type("star.core*float")],type("star.core*logical"))).
escapeType("srand",funType([type("star.core*float")],voidType)).
escapeType("rand",funType([],type("star.core*float"))).
escapeType("irand",funType([type("star.core*integer")],type("star.core*integer"))).
escapeType("_ldexp",funType([type("star.core*float"),type("star.core*float")],type("star.core*float"))).
escapeType("_frexp",funType([type("star.core*float")],tupleType([type("star.core*float"),type("star.core*integer")]))).
escapeType("_modf",funType([type("star.core*float")],tupleType([type("star.core*float"),type("star.core*integer")]))).
escapeType("_band",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_bor",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_bxor",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_blsl",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_blsr",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_basr",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_bnot",funType([type("star.core*integer")],type("star.core*integer"))).
escapeType("_nthb",funType([type("star.core*integer"),type("star.core*integer")],type("star.core*logical"))).
escapeType("_get_file",funType([type("star.core*string")],type("star.core*string"))).
escapeType("_put_file",funType([type("star.core*string"),type("star.core*string")],tpFun("star.core*resultType",0))).
escapeType("_cwd",funType([],type("star.core*string"))).
escapeType("_cd",funType([type("star.core*string")],tpFun("star.core*resultType",0))).
escapeType("_rm",funType([type("star.core*string")],tpFun("star.core*resultType",0))).
escapeType("_mv",funType([type("star.core*string"),type("star.core*string")],tpFun("star.core*resultType",0))).
escapeType("_mkdir",funType([type("star.core*string"),type("star.core*integer")],tpFun("star.core*resultType",0))).
escapeType("_rmdir",funType([type("star.core*string")],tpFun("star.core*resultType",0))).
escapeType("_isdir",funType([type("star.core*string")],type("star.core*logical"))).
escapeType("_chmod",funType([type("star.core*string"),type("star.core*integer")],tpFun("star.core*resultType",0))).
escapeType("_ls",funType([type("star.core*string")],typeExp(tpFun("star.core*list",1),[type("star.core*string")]))).
escapeType("_file_mode",funType([type("star.core*string")],type("star.core*integer"))).
escapeType("_file_present",funType([type("star.core*string")],type("star.core*logical"))).
escapeType("_file_type",funType([type("star.core*string")],type("star.core*integer"))).
escapeType("_file_size",funType([type("star.core*string")],type("star.core*integer"))).
escapeType("_file_modified",funType([type("star.core*string")],type("star.core*integer"))).
escapeType("_file_date",funType([type("star.core*string")],tupleType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer")]))).
escapeType("_openInFile",funType([type("star.core*string"),type("star.core*integer")],type("star.io*fileHandle"))).
escapeType("_openOutFile",funType([type("star.core*string"),type("star.core*integer")],type("star.io*fileHandle"))).
escapeType("_openAppendFile",funType([type("star.core*string"),type("star.core*integer")],type("star.io*fileHandle"))).
escapeType("_openAppendIOFile",funType([type("star.core*string"),type("star.core*integer")],type("star.io*fileHandle"))).
escapeType("_popen",funType([type("star.core*string"),typeExp(tpFun("star.core*list",1),[type("star.core*string")]),typeExp(tpFun("star.core*list",1),[tupleType([type("star.core*string"),type("star.core*string")])])],tupleType([type("star.io*fileHandle"),type("star.io*fileHandle"),type("star.io*fileHandle")]))).
escapeType("_close",funType([type("star.io*fileHandle")],tpFun("star.core*resultType",0))).
escapeType("_end_of_file",funType([type("star.io*fileHandle")],type("star.core*logical"))).
escapeType("_ready",funType([type("star.io*fileHandle")],type("star.core*logical"))).
escapeType("_inchars",funType([type("star.io*fileHandle"),type("star.core*integer")],type("star.core*string"))).
escapeType("_inbytes",funType([type("star.io*fileHandle"),type("star.core*integer")],typeExp(tpFun("star.core*list",1),[type("star.core*integer")]))).
escapeType("_inchar",funType([type("star.io*fileHandle")],type("star.core*integer"))).
escapeType("_inbyte",funType([type("star.io*fileHandle")],type("star.core*integer"))).
escapeType("_inline",funType([type("star.io*fileHandle")],type("star.core*string"))).
escapeType("_intext",funType([type("star.io*fileHandle"),type("star.core*string")],type("star.core*string"))).
escapeType("_outch",funType([type("star.io*fileHandle"),type("star.core*integer")],tpFun("star.core*resultType",0))).
escapeType("_outbyte",funType([type("star.io*fileHandle"),type("star.core*integer")],tpFun("star.core*resultType",0))).
escapeType("_outbytes",funType([type("star.io*fileHandle"),typeExp(tpFun("star.core*list",1),[type("star.core*integer")])],tpFun("star.core*resultType",0))).
escapeType("_outtext",funType([type("star.io*fileHandle"),type("star.core*string")],tpFun("star.core*resultType",0))).
escapeType("_stdfile",funType([type("star.core*integer")],type("star.io*fileHandle"))).
escapeType("_fposition",funType([type("star.io*fileHandle")],type("star.core*integer"))).
escapeType("_fseek",funType([type("star.io*fileHandle"),type("star.core*integer")],tpFun("star.core*resultType",0))).
escapeType("_flush",funType([type("star.io*fileHandle")],tpFun("star.core*resultType",0))).
escapeType("_flushall",funType([],tpFun("star.core*resultType",0))).
escapeType("_setfileencoding",funType([type("star.io*fileHandle"),type("star.core*integer")],tpFun("star.core*resultType",0))).
escapeType("_install_pkg",funType([type("star.core*string")],typeExp(tpFun("star.core*list",1),[tupleType([type("star.core*string"),type("star.core*string")])]))).
escapeType("_pkg_is_present",funType([type("star.core*string"),type("star.core*string"),type("star.core*string"),type("star.core*string")],type("star.core*logical"))).
escapeType("_logmsg",funType([type("star.core*string")],voidType)).
escapeType("_connect",funType([type("star.core*string"),type("star.core*integer"),type("star.core*integer"),type("star.io*fileHandle"),type("star.io*fileHandle")],tpFun("star.core*resultType",0))).
escapeType("_listen",funType([type("star.core*integer"),type("star.io*fileHandle")],tpFun("star.core*resultType",0))).
escapeType("_accept",funType([type("star.io*fileHandle")],tupleType([type("star.io*fileHandle"),type("star.io*fileHandle"),type("star.core*string"),type("star.core*integer"),type("star.core*string")]))).
escapeType("_udpPort",funType([type("star.core*integer"),type("star.io*udpHandle")],tpFun("star.core*resultType",0))).
escapeType("_udpGet",funType([type("star.io*udpHandle")],tupleType([type("star.core*string"),type("star.core*string"),type("star.core*integer")]))).
escapeType("_udpSend",funType([type("star.io*udpHandle"),type("star.core*string"),type("star.core*string"),type("star.core*integer")],tpFun("star.core*resultType",0))).
escapeType("_udpClose",funType([type("star.io*udpHandle")],tpFun("star.core*resultType",0))).
escapeType("hosttoip",funType([type("star.core*string")],typeExp(tpFun("star.core*list",1),[type("star.core*string")]))).
escapeType("iptohost",funType([type("star.core*string")],type("star.core*string"))).
escapeType("delay",funType([type("star.core*float")],tpFun("star.core*resultType",0))).
escapeType("sleep",funType([type("star.core*float")],tpFun("star.core*resultType",0))).
escapeType("now",funType([],type("star.core*float"))).
escapeType("today",funType([],type("star.core*float"))).
escapeType("ticks",funType([],type("star.core*float"))).
escapeType("_time2date",funType([type("star.core*float")],tupleType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*float"),type("star.core*integer"),type("star.core*integer")]))).
escapeType("_time2utc",funType([type("star.core*float")],tupleType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*float"),type("star.core*integer"),type("star.core*integer")]))).
escapeType("_date2time",funType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*float"),type("star.core*integer")],type("star.core*float"))).
escapeType("_utc2time",funType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*float"),type("star.core*integer")],type("star.core*float"))).
escapeType("_isCcChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isCfChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isCnChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isCoChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isCsChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isLlChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isLmChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isLoChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isLtChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isLuChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isMcChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isMeChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isMnChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isNdChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isNlChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isNoChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isPcChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isPdChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isPeChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isPfChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isPiChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isPoChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isPsChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isScChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isSkChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isSmChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isSoChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isZlChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isZpChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isZsChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_isLetterChar",funType([type("star.core*integer")],type("star.core*logical"))).
escapeType("_digitCode",funType([type("star.core*integer")],type("star.core*integer"))).
escapeType("_int2str",funType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer")],type("star.core*string"))).
escapeType("_flt2str",funType([type("star.core*float"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*logical")],type("star.core*string"))).
escapeType("_int_format",funType([type("star.core*integer"),type("star.core*string")],type("star.core*string"))).
escapeType("_flt_format",funType([type("star.core*float"),type("star.core*string")],type("star.core*string"))).
escapeType("_str2flt",funType([type("star.core*string")],type("star.core*float"))).
escapeType("_str2int",funType([type("star.core*string")],type("star.core*integer"))).
escapeType("_str_eq",funType([type("star.core*string"),type("star.core*string")],type("star.core*logical"))).
escapeType("_str_lt",funType([type("star.core*string"),type("star.core*string")],type("star.core*logical"))).
escapeType("_str_ge",funType([type("star.core*string"),type("star.core*string")],type("star.core*logical"))).
escapeType("_str_hash",funType([type("star.core*string")],type("star.core*integer"))).
escapeType("_str_len",funType([type("star.core*string")],type("star.core*integer"))).
escapeType("_str_gen",funType([type("star.core*string")],type("star.core*string"))).
escapeType("_stringOf",univType(kVar("t"),funType([kVar("t"),type("star.core*integer"),type("star.core*integer")],type("star.core*string")))).
escapeType("_trim",funType([type("star.core*string"),type("star.core*integer")],type("star.core*string"))).
escapeType("explode",funType([type("star.core*string")],typeExp(tpFun("star.core*list",1),[type("star.core*integer")]))).
escapeType("implode",funType([typeExp(tpFun("star.core*list",1),[type("star.core*integer")])],type("star.core*string"))).
escapeType("_str_find",funType([type("star.core*string"),type("star.core*string"),type("star.core*integer")],type("star.core*integer"))).
escapeType("_sub_str",funType([type("star.core*string"),type("star.core*integer"),type("star.core*integer")],type("star.core*string"))).
escapeType("_str_split",funType([type("star.core*string"),type("star.core*integer")],tupleType([type("star.core*string"),type("star.core*string")]))).
escapeType("_str_concat",funType([type("star.core*string"),type("star.core*string")],type("star.core*string"))).
escapeType("_str_start",funType([type("star.core*string"),type("star.core*string")],type("star.core*logical"))).
escapeType("_str_multicat",funType([typeExp(tpFun("star.core*list",1),[type("star.core*string")])],type("star.core*string"))).
escapeType("getenv",funType([type("star.core*string"),type("star.core*string")],type("star.core*string"))).
escapeType("setenv",funType([type("star.core*string"),type("star.core*string")],tpFun("star.core*resultType",0))).
escapeType("envir",funType([],typeExp(tpFun("star.core*list",1),[tupleType([type("star.core*string"),type("star.core*string")])]))).
escapeType("getlogin",funType([],type("star.core*string"))).
escapeType("_fork",funType([funType([],tpFun("star.core*resultType",0)),tupleType([type("star.core*string")])],type("star.thread*thread"))).
escapeType("_thread",funType([],type("star.thread*thread"))).
escapeType("kill",funType([type("star.thread*thread")],tpFun("star.core*resultType",0))).
escapeType("thread_state",funType([type("star.thread*thread")],type("star.thread*processState"))).
escapeType("waitfor",funType([type("star.thread*thread")],tpFun("star.core*resultType",0))).
escapeType("_shell",funType([type("star.core*string"),typeExp(tpFun("star.core*list",1),[type("star.core*string")]),typeExp(tpFun("star.core*list",1),[tupleType([type("star.core*string"),type("star.core*string")])])],type("star.core*integer"))).
escapeType("_newLock",funType([],type("star.thread*lock"))).
escapeType("_acquireLock",funType([type("star.thread*lock"),type("star.core*float")],tpFun("star.core*resultType",0))).
escapeType("_waitLock",funType([type("star.thread*lock"),type("star.core*float")],tpFun("star.core*resultType",0))).
escapeType("_releaseLock",funType([type("star.thread*lock")],tpFun("star.core*resultType",0))).
escapeType("_ins_debug",funType([],voidType)).
escapeType("_stackTrace",funType([],voidType)).
isEscape("_exit").
isEscape("_command_line").
isEscape("_command_opts").
isEscape("_identical").
isEscape("_defined").
isEscape("_int_plus").
isEscape("_int_minus").
isEscape("_int_times").
isEscape("_int_div").
isEscape("_int_mod").
isEscape("_flt_plus").
isEscape("_flt_minus").
isEscape("_flt_times").
isEscape("_flt_div").
isEscape("_flt_mod").
isEscape("_int_abs").
isEscape("_flt_abs").
isEscape("_int_eq").
isEscape("_int_lt").
isEscape("_int_ge").
isEscape("_flt_eq").
isEscape("_flt_lt").
isEscape("_flt_ge").
isEscape("_int2flt").
isEscape("_flt2int").
isEscape("_flt_hash").
isEscape("_pwr").
isEscape("sqrt").
isEscape("exp").
isEscape("log").
isEscape("log10").
isEscape("pi").
isEscape("sin").
isEscape("cos").
isEscape("tan").
isEscape("asin").
isEscape("acos").
isEscape("atan").
isEscape("trunc").
isEscape("floor").
isEscape("ceil").
isEscape("integral").
isEscape("srand").
isEscape("rand").
isEscape("irand").
isEscape("_ldexp").
isEscape("_frexp").
isEscape("_modf").
isEscape("_band").
isEscape("_bor").
isEscape("_bxor").
isEscape("_blsl").
isEscape("_blsr").
isEscape("_basr").
isEscape("_bnot").
isEscape("_nthb").
isEscape("_get_file").
isEscape("_put_file").
isEscape("_cwd").
isEscape("_cd").
isEscape("_rm").
isEscape("_mv").
isEscape("_mkdir").
isEscape("_rmdir").
isEscape("_isdir").
isEscape("_chmod").
isEscape("_ls").
isEscape("_file_mode").
isEscape("_file_present").
isEscape("_file_type").
isEscape("_file_size").
isEscape("_file_modified").
isEscape("_file_date").
isEscape("_openInFile").
isEscape("_openOutFile").
isEscape("_openAppendFile").
isEscape("_openAppendIOFile").
isEscape("_popen").
isEscape("_close").
isEscape("_end_of_file").
isEscape("_ready").
isEscape("_inchars").
isEscape("_inbytes").
isEscape("_inchar").
isEscape("_inbyte").
isEscape("_inline").
isEscape("_intext").
isEscape("_outch").
isEscape("_outbyte").
isEscape("_outbytes").
isEscape("_outtext").
isEscape("_stdfile").
isEscape("_fposition").
isEscape("_fseek").
isEscape("_flush").
isEscape("_flushall").
isEscape("_setfileencoding").
isEscape("_install_pkg").
isEscape("_pkg_is_present").
isEscape("_logmsg").
isEscape("_connect").
isEscape("_listen").
isEscape("_accept").
isEscape("_udpPort").
isEscape("_udpGet").
isEscape("_udpSend").
isEscape("_udpClose").
isEscape("hosttoip").
isEscape("iptohost").
isEscape("delay").
isEscape("sleep").
isEscape("now").
isEscape("today").
isEscape("ticks").
isEscape("_time2date").
isEscape("_time2utc").
isEscape("_date2time").
isEscape("_utc2time").
isEscape("_isCcChar").
isEscape("_isCfChar").
isEscape("_isCnChar").
isEscape("_isCoChar").
isEscape("_isCsChar").
isEscape("_isLlChar").
isEscape("_isLmChar").
isEscape("_isLoChar").
isEscape("_isLtChar").
isEscape("_isLuChar").
isEscape("_isMcChar").
isEscape("_isMeChar").
isEscape("_isMnChar").
isEscape("_isNdChar").
isEscape("_isNlChar").
isEscape("_isNoChar").
isEscape("_isPcChar").
isEscape("_isPdChar").
isEscape("_isPeChar").
isEscape("_isPfChar").
isEscape("_isPiChar").
isEscape("_isPoChar").
isEscape("_isPsChar").
isEscape("_isScChar").
isEscape("_isSkChar").
isEscape("_isSmChar").
isEscape("_isSoChar").
isEscape("_isZlChar").
isEscape("_isZpChar").
isEscape("_isZsChar").
isEscape("_isLetterChar").
isEscape("_digitCode").
isEscape("_int2str").
isEscape("_flt2str").
isEscape("_int_format").
isEscape("_flt_format").
isEscape("_str2flt").
isEscape("_str2int").
isEscape("_str_eq").
isEscape("_str_lt").
isEscape("_str_ge").
isEscape("_str_hash").
isEscape("_str_len").
isEscape("_str_gen").
isEscape("_stringOf").
isEscape("_trim").
isEscape("explode").
isEscape("implode").
isEscape("_str_find").
isEscape("_sub_str").
isEscape("_str_split").
isEscape("_str_concat").
isEscape("_str_start").
isEscape("_str_multicat").
isEscape("getenv").
isEscape("setenv").
isEscape("envir").
isEscape("getlogin").
isEscape("_fork").
isEscape("_thread").
isEscape("kill").
isEscape("thread_state").
isEscape("waitfor").
isEscape("_shell").
isEscape("_newLock").
isEscape("_acquireLock").
isEscape("_waitLock").
isEscape("_releaseLock").
isEscape("_ins_debug").
isEscape("_stackTrace").
