/* Automatically generated, do not edit */

:-module(escapes,[isEscape/2,escapeType/2]).

escapeType("_exit",funType(tplType([type("star.core*integer")]),tplType([]))).
escapeType("_abort",allType(kVar("a"),funType(tplType([kVar("a"),type("star.core*string")]),tplType([])))).
escapeType("_definedLbl",funType(tplType([type("star.core*string"),type("star.core*integer")]),type("star.core*boolean"))).
escapeType("_callLbl",funType(tplType([type("star.core*string"),type("star.core*integer"),tpExp(tpFun("star.core*cons",1),tpExp(tpFun("star.core*cons",1),type("star.core*string")))]),tplType([]))).
escapeType("_int_plus",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_int_minus",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_int_times",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_int_div",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_int_mod",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_int_hash",funType(tplType([type("star.core*integer")]),type("star.core*integer"))).
escapeType("_int_gcd",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_flt_plus",funType(tplType([type("star.core*float"),type("star.core*float")]),type("star.core*float"))).
escapeType("_flt_minus",funType(tplType([type("star.core*float"),type("star.core*float")]),type("star.core*float"))).
escapeType("_flt_times",funType(tplType([type("star.core*float"),type("star.core*float")]),type("star.core*float"))).
escapeType("_flt_div",funType(tplType([type("star.core*float"),type("star.core*float")]),type("star.core*float"))).
escapeType("_flt_mod",funType(tplType([type("star.core*float"),type("star.core*float")]),type("star.core*float"))).
escapeType("_int_abs",funType(tplType([type("star.core*integer")]),type("star.core*integer"))).
escapeType("_flt_abs",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("_int_eq",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*boolean"))).
escapeType("_int_lt",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*boolean"))).
escapeType("_int_ge",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*boolean"))).
escapeType("_flt_eq",funType(tplType([type("star.core*float"),type("star.core*float"),type("star.core*float")]),type("star.core*boolean"))).
escapeType("_flt_lt",funType(tplType([type("star.core*float"),type("star.core*float")]),type("star.core*boolean"))).
escapeType("_flt_ge",funType(tplType([type("star.core*float"),type("star.core*float")]),type("star.core*boolean"))).
escapeType("_int2flt",funType(tplType([type("star.core*integer")]),type("star.core*float"))).
escapeType("_flt2int",funType(tplType([type("star.core*float")]),type("star.core*integer"))).
escapeType("_bits_float",funType(tplType([type("star.core*integer")]),type("star.core*float"))).
escapeType("_float_bits",funType(tplType([type("star.core*float")]),type("star.core*integer"))).
escapeType("_flt_hash",funType(tplType([type("star.core*float")]),type("star.core*integer"))).
escapeType("_flt_pwr",funType(tplType([type("star.core*float"),type("star.core*float")]),type("star.core*float"))).
escapeType("_big_plus",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*bigint"))).
escapeType("_big_minus",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*bigint"))).
escapeType("_big_times",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*bigint"))).
escapeType("_big_div",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),tplType([type("star.core*bigint"),type("star.core*bigint")]))).
escapeType("_big_bitand",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*bigint"))).
escapeType("_big_bitor",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*bigint"))).
escapeType("_big_bitxor",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*bigint"))).
escapeType("_big_bitnot",funType(tplType([type("star.core*bigint")]),type("star.core*bigint"))).
escapeType("_big_gcd",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*bigint"))).
escapeType("_big_hash",funType(tplType([type("star.core*bigint")]),type("star.core*integer"))).
escapeType("_big_eq",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*boolean"))).
escapeType("_big_lt",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*boolean"))).
escapeType("_big_ge",funType(tplType([type("star.core*bigint"),type("star.core*bigint")]),type("star.core*boolean"))).
escapeType("_int2big",funType(tplType([type("star.core*integer")]),type("star.core*bigint"))).
escapeType("_big2int",funType(tplType([type("star.core*bigint")]),tpExp(tpFun("star.core*option",1),type("star.core*integer")))).
escapeType("_ints2big",funType(tplType([tpExp(tpFun("star.core*cons",1),type("star.core*integer"))]),type("star.core*bigint"))).
escapeType("_big2ints",funType(tplType([type("star.core*bigint")]),tpExp(tpFun("star.core*cons",1),type("star.core*integer")))).
escapeType("_str2big",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*option",1),type("star.core*bigint")))).
escapeType("_big2str",funType(tplType([type("star.core*bigint")]),type("star.core*string"))).
escapeType("_big_format",funType(tplType([type("star.core*bigint"),type("star.core*string")]),type("star.core*string"))).
escapeType("_fiber_eq",allType(kVar("s"),allType(kVar("r"),funType(tplType([tpExp(tpExp(tpFun("star.fiber*fiber",2),kVar("s")),kVar("r")),tpExp(tpExp(tpFun("star.fiber*fiber",2),kVar("s")),kVar("r"))]),type("star.core*boolean"))))).
escapeType("_new_fiber",allType(kVar("s"),allType(kVar("r"),funType(tplType([funType(tplType([tpExp(tpExp(tpFun("star.fiber*fiber",2),kVar("r")),kVar("s")),kVar("r")]),kVar("s"))]),tpExp(tpExp(tpFun("star.fiber*fiber",2),kVar("r")),kVar("s")))))).
escapeType("_spawn",allType(kVar("s"),allType(kVar("r"),funType(tplType([funType(tplType([tpExp(tpExp(tpFun("star.fiber*fiber",2),kVar("r")),kVar("s"))]),kVar("s"))]),kVar("s"))))).
escapeType("_suspend",allType(kVar("s"),allType(kVar("r"),funType(tplType([tpExp(tpExp(tpFun("star.fiber*fiber",2),kVar("r")),kVar("s")),kVar("s")]),kVar("r"))))).
escapeType("_retire",allType(kVar("s"),allType(kVar("r"),funType(tplType([tpExp(tpExp(tpFun("star.fiber*fiber",2),kVar("r")),kVar("s")),kVar("s")]),tplType([]))))).
escapeType("_resume",allType(kVar("s"),allType(kVar("r"),funType(tplType([tpExp(tpExp(tpFun("star.fiber*fiber",2),kVar("r")),kVar("s")),kVar("r")]),kVar("s"))))).
escapeType("sqrt",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("exp",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("log",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("log10",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("pi",funType(tplType([]),type("star.core*float"))).
escapeType("sin",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("cos",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("tan",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("asin",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("acos",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("atan",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("trunc",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("floor",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("ceil",funType(tplType([type("star.core*float")]),type("star.core*float"))).
escapeType("integral",funType(tplType([type("star.core*float")]),type("star.core*boolean"))).
escapeType("_irand",funType(tplType([type("star.core*integer")]),type("star.core*integer"))).
escapeType("_random",funType(tplType([]),type("star.core*float"))).
escapeType("_seed",funType(tplType([type("star.core*integer")]),tplType([]))).
escapeType("_ldexp",funType(tplType([type("star.core*float"),type("star.core*integer")]),type("star.core*float"))).
escapeType("_frexp",funType(tplType([type("star.core*float")]),tplType([type("star.core*float"),type("star.core*integer")]))).
escapeType("_modf",funType(tplType([type("star.core*float")]),tplType([type("star.core*float"),type("star.core*integer")]))).
escapeType("_band",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_bor",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_bxor",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_blsl",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_blsr",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_basr",funType(tplType([type("star.core*integer"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_bnot",funType(tplType([type("star.core*integer")]),type("star.core*integer"))).
escapeType("_cell",allType(kVar("t"),funType(tplType([kVar("t")]),refType(kVar("t"))))).
escapeType("_get",allType(kVar("t"),funType(tplType([refType(kVar("t"))]),kVar("t")))).
escapeType("_assign",allType(kVar("t"),funType(tplType([refType(kVar("t")),kVar("t")]),tplType([])))).
escapeType("_overwrite",allType(kVar("t"),funType(tplType([kVar("t"),kVar("t")]),kVar("t")))).
escapeType("_tuple_nth",allType(kVar("t"),allType(kVar("e"),funType(tplType([kVar("t"),type("star.core*integer")]),kVar("e"))))).
escapeType("_tuple_set_nth",allType(kVar("t"),allType(kVar("e"),funType(tplType([kVar("t"),type("star.core*integer"),kVar("e")]),kVar("t"))))).
escapeType("_cwd",funType(tplType([]),type("star.core*string"))).
escapeType("_cd",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_rm",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_mv",funType(tplType([type("star.core*string"),type("star.core*string")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_mkdir",funType(tplType([type("star.core*string"),type("star.core*integer")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_rmdir",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_isdir",funType(tplType([type("star.core*string")]),type("star.core*boolean"))).
escapeType("_file_chmod",funType(tplType([type("star.core*string"),type("star.core*integer")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_ls",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*cons",1),type("star.core*string")))).
escapeType("_repo",funType(tplType([]),type("star.core*string"))).
escapeType("_file_mode",funType(tplType([type("star.core*string")]),type("star.core*integer"))).
escapeType("_file_present",funType(tplType([type("star.core*string")]),type("star.core*boolean"))).
escapeType("_file_type",funType(tplType([type("star.core*string")]),type("star.core*integer"))).
escapeType("_file_size",funType(tplType([type("star.core*string")]),type("star.core*integer"))).
escapeType("_file_modified",funType(tplType([type("star.core*string")]),type("star.core*integer"))).
escapeType("_file_date",funType(tplType([type("star.core*string")]),tplType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer")]))).
escapeType("_openInFile",funType(tplType([type("star.core*string"),type("star.core*integer")]),type("star.file*fileHandle"))).
escapeType("_openOutFile",funType(tplType([type("star.core*string"),type("star.core*integer")]),type("star.file*fileHandle"))).
escapeType("_openAppendFile",funType(tplType([type("star.core*string"),type("star.core*integer")]),type("star.file*fileHandle"))).
escapeType("_openAppendIOFile",funType(tplType([type("star.core*string"),type("star.core*integer")]),type("star.file*fileHandle"))).
escapeType("_popen",funType(tplType([type("star.core*string"),tpExp(tpFun("star.core*cons",1),type("star.core*string")),tpExp(tpFun("star.core*cons",1),tplType([type("star.core*string"),type("star.core*string")]))]),tplType([type("star.file*fileHandle"),type("star.file*fileHandle"),type("star.file*fileHandle")]))).
escapeType("_close",funType(tplType([type("star.file*fileHandle")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_end_of_file",funType(tplType([type("star.file*fileHandle")]),type("star.core*boolean"))).
escapeType("_ready_to_read",funType(tplType([type("star.file*fileHandle")]),type("star.core*boolean"))).
escapeType("_ready_to_write",funType(tplType([type("star.file*fileHandle")]),type("star.core*boolean"))).
escapeType("_inchars",funType(tplType([type("star.file*fileHandle"),type("star.core*integer")]),type("star.core*string"))).
escapeType("_inbytes",funType(tplType([type("star.file*fileHandle"),type("star.core*integer")]),tpExp(tpFun("star.core*cons",1),type("star.core*integer")))).
escapeType("_enqueue_read",funType(tplType([type("star.file*fileHandle"),type("star.core*integer")]),tpExp(tpFun("star.core*future",1),tpExp(tpFun("star.core*cons",1),type("star.core*integer"))))).
escapeType("_inchar",funType(tplType([type("star.file*fileHandle")]),type("star.core*integer"))).
escapeType("_inbyte",funType(tplType([type("star.file*fileHandle")]),type("star.core*integer"))).
escapeType("_inline",funType(tplType([type("star.file*fileHandle")]),type("star.core*string"))).
escapeType("_inline_async",funType(tplType([type("star.file*fileHandle")]),tpExp(tpFun("star.core*future",1),type("star.core*string")))).
escapeType("_intext",funType(tplType([type("star.file*fileHandle"),type("star.core*string")]),type("star.core*string"))).
escapeType("_outchar",funType(tplType([type("star.file*fileHandle"),type("star.core*integer")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_outbyte",funType(tplType([type("star.file*fileHandle"),type("star.core*integer")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_outbytes",funType(tplType([type("star.file*fileHandle"),tpExp(tpFun("star.core*cons",1),type("star.core*integer"))]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_outtext",funType(tplType([type("star.file*fileHandle"),type("star.core*string")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_stdfile",funType(tplType([type("star.core*integer")]),type("star.file*fileHandle"))).
escapeType("_fposition",funType(tplType([type("star.file*fileHandle")]),type("star.core*integer"))).
escapeType("_fseek",funType(tplType([type("star.file*fileHandle"),type("star.core*integer")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_flush",funType(tplType([type("star.file*fileHandle")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_flushall",funType(tplType([]),tplType([]))).
escapeType("_setfileencoding",funType(tplType([type("star.file*fileHandle"),type("star.core*integer")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_get_file",funType(tplType([type("star.core*string")]),type("star.core*string"))).
escapeType("_put_file",funType(tplType([type("star.core*string"),type("star.core*string")]),tplType([]))).
escapeType("_show",funType(tplType([type("star.core*string")]),tplType([]))).
escapeType("_install_pkg",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*cons",1),tplType([type("star.core*string"),type("star.core*string")])))).
escapeType("_pkg_is_present",funType(tplType([type("star.core*string"),type("star.core*string")]),type("star.core*boolean"))).
escapeType("_in_manifest",funType(tplType([type("star.core*string"),type("star.core*string"),type("star.core*string")]),type("star.core*boolean"))).
escapeType("_locate_in_manifest",funType(tplType([type("star.core*string"),type("star.core*string"),type("star.core*string")]),type("star.core*string"))).
escapeType("_logmsg",funType(tplType([type("star.core*string")]),tplType([]))).
escapeType("_display_depth",funType(tplType([]),type("star.core*integer"))).
escapeType("_connect",funType(tplType([type("star.core*string"),type("star.core*integer"),type("star.core*integer")]),tplType([type("star.file*fileHandle"),type("star.file*fileHandle")]))).
escapeType("_listen",funType(tplType([type("star.core*integer")]),type("star.file*fileHandle"))).
escapeType("_accept",funType(tplType([type("star.file*fileHandle")]),tplType([type("star.file*fileHandle"),type("star.file*fileHandle"),type("star.core*string"),type("star.core*integer"),type("star.core*string")]))).
escapeType("_hosttoip",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*cons",1),type("star.core*string")))).
escapeType("_iptohost",funType(tplType([type("star.core*string")]),type("star.core*string"))).
escapeType("_delay",funType(tplType([type("star.core*float")]),tplType([]))).
escapeType("_sleep",funType(tplType([type("star.core*float")]),tplType([]))).
escapeType("_now",funType(tplType([]),type("star.core*float"))).
escapeType("_today",funType(tplType([]),type("star.core*float"))).
escapeType("_ticks",funType(tplType([]),type("star.core*integer"))).
escapeType("_time2date",funType(tplType([type("star.core*float")]),tplType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*float"),type("star.core*integer")]))).
escapeType("_time2utc",funType(tplType([type("star.core*float")]),tplType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*float"),type("star.core*integer")]))).
escapeType("_date2time",funType(tplType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*float"),type("star.core*integer")]),type("star.core*float"))).
escapeType("_utc2time",funType(tplType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*float"),type("star.core*integer")]),type("star.core*float"))).
escapeType("_fmttime",funType(tplType([type("star.core*float"),type("star.core*string")]),type("star.core*string"))).
escapeType("_formattime",funType(tplType([type("star.core*float"),type("star.core*string")]),type("star.core*string"))).
escapeType("_parsetime",funType(tplType([type("star.core*string"),type("star.core*string")]),tpExp(tpFun("star.core*option",1),type("star.core*float")))).
escapeType("_uniCodeCategory",funType(tplType([type("star.core*char")]),type("star.core*integer"))).
escapeType("_isCcChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isCfChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isCnChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isCoChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isCsChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isLlChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isLmChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isLoChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isLtChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isLuChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isMcChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isMeChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isMnChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isNdChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isNlChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isNoChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isPcChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isPdChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isPeChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isPfChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isPiChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isPoChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isPsChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isScChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isSkChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isSmChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isSoChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isZlChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isZpChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isZsChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isLetterChar",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_digitCode",funType(tplType([type("star.core*char")]),type("star.core*integer"))).
escapeType("_codePoint",funType(tplType([type("star.core*char")]),type("star.core*integer"))).
escapeType("_char",funType(tplType([type("star.core*integer")]),type("star.core*char"))).
escapeType("_isIDStart",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_isIDContinue",funType(tplType([type("star.core*char")]),type("star.core*boolean"))).
escapeType("_int2str",funType(tplType([type("star.core*integer"),type("star.core*integer"),type("star.core*integer"),type("star.core*integer")]),type("star.core*string"))).
escapeType("_flt2str",funType(tplType([type("star.core*float"),type("star.core*integer"),type("star.core*char"),type("star.core*boolean")]),type("star.core*string"))).
escapeType("_int_format",funType(tplType([type("star.core*integer"),type("star.core*string")]),type("star.core*string"))).
escapeType("_flt_format",funType(tplType([type("star.core*float"),type("star.core*string")]),type("star.core*string"))).
escapeType("_str2flt",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*option",1),type("star.core*float")))).
escapeType("_str2int",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*option",1),type("star.core*integer")))).
escapeType("_chr_eq",funType(tplType([type("star.core*char"),type("star.core*char")]),type("star.core*boolean"))).
escapeType("_chr_lt",funType(tplType([type("star.core*char"),type("star.core*char")]),type("star.core*boolean"))).
escapeType("_chr_ge",funType(tplType([type("star.core*char"),type("star.core*char")]),type("star.core*boolean"))).
escapeType("_chr_hash",funType(tplType([type("star.core*char")]),type("star.core*integer"))).
escapeType("_chr_quote",funType(tplType([type("star.core*char")]),type("star.core*string"))).
escapeType("_chr_format",funType(tplType([type("star.core*char"),type("star.core*string")]),type("star.core*string"))).
escapeType("_str_eq",funType(tplType([type("star.core*string"),type("star.core*string")]),type("star.core*boolean"))).
escapeType("_str_lt",funType(tplType([type("star.core*string"),type("star.core*string")]),type("star.core*boolean"))).
escapeType("_str_ge",funType(tplType([type("star.core*string"),type("star.core*string")]),type("star.core*boolean"))).
escapeType("_str_hash",funType(tplType([type("star.core*string")]),type("star.core*integer"))).
escapeType("_str_len",funType(tplType([type("star.core*string")]),type("star.core*integer"))).
escapeType("_str_gen",funType(tplType([type("star.core*string")]),type("star.core*string"))).
escapeType("_stringOf",allType(kVar("t"),funType(tplType([kVar("t"),type("star.core*integer")]),type("star.core*string")))).
escapeType("_explode",funType(tplType([type("star.core*string")]),tpExp(tpFun("star.core*cons",1),type("star.core*char")))).
escapeType("_implode",funType(tplType([tpExp(tpFun("star.core*cons",1),type("star.core*char"))]),type("star.core*string"))).
escapeType("_str_find",funType(tplType([type("star.core*string"),type("star.core*string"),type("star.core*integer")]),type("star.core*integer"))).
escapeType("_sub_str",funType(tplType([type("star.core*string"),type("star.core*integer"),type("star.core*integer")]),type("star.core*string"))).
escapeType("_str_split",funType(tplType([type("star.core*string"),type("star.core*integer")]),tplType([type("star.core*string"),type("star.core*string")]))).
escapeType("_str_concat",funType(tplType([type("star.core*string"),type("star.core*string")]),type("star.core*string"))).
escapeType("_str_reverse",funType(tplType([type("star.core*string")]),type("star.core*string"))).
escapeType("_str_start",funType(tplType([type("star.core*string"),type("star.core*string")]),type("star.core*boolean"))).
escapeType("_str_splice",funType(tplType([type("star.core*string"),type("star.core*integer"),type("star.core*integer"),type("star.core*string")]),type("star.core*string"))).
escapeType("_str_multicat",funType(tplType([tpExp(tpFun("star.core*cons",1),type("star.core*string"))]),type("star.core*string"))).
escapeType("_str_hdtl",funType(tplType([type("star.core*string")]),tplType([type("star.core*char"),type("star.core*string")]))).
escapeType("_str_back",funType(tplType([type("star.core*string")]),tplType([type("star.core*string"),type("star.core*char")]))).
escapeType("_str_cons",funType(tplType([type("star.core*char"),type("star.core*string")]),type("star.core*string"))).
escapeType("_code2str",funType(tplType([type("star.core*char")]),type("star.core*string"))).
escapeType("_str_apnd",funType(tplType([type("star.core*string"),type("star.core*char")]),type("star.core*string"))).
escapeType("_str_quote",funType(tplType([type("star.core*string")]),type("star.core*string"))).
escapeType("_str_format",funType(tplType([type("star.core*string"),type("star.core*string")]),type("star.core*string"))).
escapeType("_getenv",funType(tplType([type("star.core*string"),type("star.core*string")]),type("star.core*string"))).
escapeType("_setenv",funType(tplType([type("star.core*string"),type("star.core*string")]),tplType([]))).
escapeType("_envir",funType(tplType([]),tpExp(tpFun("star.core*cons",1),tplType([type("star.core*string"),type("star.core*string")])))).
escapeType("_getlogin",funType(tplType([]),type("star.core*string"))).
escapeType("_fork",funType(tplType([funType(tplType([]),tpExp(tpFun("star.core*result",2),type("star.core*string"))),tplType([])]),type("star.thread*thread"))).
escapeType("_thread",funType(tplType([]),type("star.thread*thread"))).
escapeType("_kill",funType(tplType([type("star.thread*thread")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_thread_state",funType(tplType([type("star.thread*thread")]),type("star.thread*threadState"))).
escapeType("_waitfor",funType(tplType([type("star.thread*thread")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_shell",funType(tplType([type("star.core*string"),tpExp(tpFun("star.core*cons",1),type("star.core*string")),tpExp(tpFun("star.core*cons",1),tplType([type("star.core*string"),type("star.core*string")]))]),type("star.core*integer"))).
escapeType("_newLock",funType(tplType([]),type("star.thread*lock"))).
escapeType("_acquireLock",funType(tplType([type("star.thread*lock"),type("star.core*float")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_waitLock",funType(tplType([type("star.thread*lock"),type("star.core*float")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_releaseLock",funType(tplType([type("star.thread*lock")]),tpExp(tpFun("star.core*result",2),type("star.core*string")))).
escapeType("_ins_debug",funType(tplType([]),tplType([]))).
escapeType("_stackTrace",funType(tplType([]),type("star.core*string"))).
isEscape("_exit",0).
isEscape("_abort",1).
isEscape("_definedLbl",2).
isEscape("_callLbl",3).
isEscape("_int_plus",4).
isEscape("_int_minus",5).
isEscape("_int_times",6).
isEscape("_int_div",7).
isEscape("_int_mod",8).
isEscape("_int_hash",9).
isEscape("_int_gcd",10).
isEscape("_flt_plus",11).
isEscape("_flt_minus",12).
isEscape("_flt_times",13).
isEscape("_flt_div",14).
isEscape("_flt_mod",15).
isEscape("_int_abs",16).
isEscape("_flt_abs",17).
isEscape("_int_eq",18).
isEscape("_int_lt",19).
isEscape("_int_ge",20).
isEscape("_flt_eq",21).
isEscape("_flt_lt",22).
isEscape("_flt_ge",23).
isEscape("_int2flt",24).
isEscape("_flt2int",25).
isEscape("_bits_float",26).
isEscape("_float_bits",27).
isEscape("_flt_hash",28).
isEscape("_flt_pwr",29).
isEscape("_big_plus",30).
isEscape("_big_minus",31).
isEscape("_big_times",32).
isEscape("_big_div",33).
isEscape("_big_bitand",34).
isEscape("_big_bitor",35).
isEscape("_big_bitxor",36).
isEscape("_big_bitnot",37).
isEscape("_big_gcd",38).
isEscape("_big_hash",39).
isEscape("_big_eq",40).
isEscape("_big_lt",41).
isEscape("_big_ge",42).
isEscape("_int2big",43).
isEscape("_big2int",44).
isEscape("_ints2big",45).
isEscape("_big2ints",46).
isEscape("_str2big",47).
isEscape("_big2str",48).
isEscape("_big_format",49).
isEscape("_fiber_eq",50).
isEscape("_new_fiber",51).
isEscape("_spawn",52).
isEscape("_suspend",53).
isEscape("_retire",54).
isEscape("_resume",55).
isEscape("sqrt",56).
isEscape("exp",57).
isEscape("log",58).
isEscape("log10",59).
isEscape("pi",60).
isEscape("sin",61).
isEscape("cos",62).
isEscape("tan",63).
isEscape("asin",64).
isEscape("acos",65).
isEscape("atan",66).
isEscape("trunc",67).
isEscape("floor",68).
isEscape("ceil",69).
isEscape("integral",70).
isEscape("_irand",71).
isEscape("_random",72).
isEscape("_seed",73).
isEscape("_ldexp",74).
isEscape("_frexp",75).
isEscape("_modf",76).
isEscape("_band",77).
isEscape("_bor",78).
isEscape("_bxor",79).
isEscape("_blsl",80).
isEscape("_blsr",81).
isEscape("_basr",82).
isEscape("_bnot",83).
isEscape("_cell",84).
isEscape("_get",85).
isEscape("_assign",86).
isEscape("_overwrite",87).
isEscape("_tuple_nth",88).
isEscape("_tuple_set_nth",89).
isEscape("_cwd",90).
isEscape("_cd",91).
isEscape("_rm",92).
isEscape("_mv",93).
isEscape("_mkdir",94).
isEscape("_rmdir",95).
isEscape("_isdir",96).
isEscape("_file_chmod",97).
isEscape("_ls",98).
isEscape("_repo",99).
isEscape("_file_mode",100).
isEscape("_file_present",101).
isEscape("_file_type",102).
isEscape("_file_size",103).
isEscape("_file_modified",104).
isEscape("_file_date",105).
isEscape("_openInFile",106).
isEscape("_openOutFile",107).
isEscape("_openAppendFile",108).
isEscape("_openAppendIOFile",109).
isEscape("_popen",110).
isEscape("_close",111).
isEscape("_end_of_file",112).
isEscape("_ready_to_read",113).
isEscape("_ready_to_write",114).
isEscape("_inchars",115).
isEscape("_inbytes",116).
isEscape("_enqueue_read",117).
isEscape("_inchar",118).
isEscape("_inbyte",119).
isEscape("_inline",120).
isEscape("_inline_async",121).
isEscape("_intext",122).
isEscape("_outchar",123).
isEscape("_outbyte",124).
isEscape("_outbytes",125).
isEscape("_outtext",126).
isEscape("_stdfile",127).
isEscape("_fposition",128).
isEscape("_fseek",129).
isEscape("_flush",130).
isEscape("_flushall",131).
isEscape("_setfileencoding",132).
isEscape("_get_file",133).
isEscape("_put_file",134).
isEscape("_show",135).
isEscape("_install_pkg",136).
isEscape("_pkg_is_present",137).
isEscape("_in_manifest",138).
isEscape("_locate_in_manifest",139).
isEscape("_logmsg",140).
isEscape("_display_depth",141).
isEscape("_connect",142).
isEscape("_listen",143).
isEscape("_accept",144).
isEscape("_hosttoip",145).
isEscape("_iptohost",146).
isEscape("_delay",147).
isEscape("_sleep",148).
isEscape("_now",149).
isEscape("_today",150).
isEscape("_ticks",151).
isEscape("_time2date",152).
isEscape("_time2utc",153).
isEscape("_date2time",154).
isEscape("_utc2time",155).
isEscape("_fmttime",156).
isEscape("_formattime",157).
isEscape("_parsetime",158).
isEscape("_uniCodeCategory",159).
isEscape("_isCcChar",160).
isEscape("_isCfChar",161).
isEscape("_isCnChar",162).
isEscape("_isCoChar",163).
isEscape("_isCsChar",164).
isEscape("_isLlChar",165).
isEscape("_isLmChar",166).
isEscape("_isLoChar",167).
isEscape("_isLtChar",168).
isEscape("_isLuChar",169).
isEscape("_isMcChar",170).
isEscape("_isMeChar",171).
isEscape("_isMnChar",172).
isEscape("_isNdChar",173).
isEscape("_isNlChar",174).
isEscape("_isNoChar",175).
isEscape("_isPcChar",176).
isEscape("_isPdChar",177).
isEscape("_isPeChar",178).
isEscape("_isPfChar",179).
isEscape("_isPiChar",180).
isEscape("_isPoChar",181).
isEscape("_isPsChar",182).
isEscape("_isScChar",183).
isEscape("_isSkChar",184).
isEscape("_isSmChar",185).
isEscape("_isSoChar",186).
isEscape("_isZlChar",187).
isEscape("_isZpChar",188).
isEscape("_isZsChar",189).
isEscape("_isLetterChar",190).
isEscape("_digitCode",191).
isEscape("_codePoint",192).
isEscape("_char",193).
isEscape("_isIDStart",194).
isEscape("_isIDContinue",195).
isEscape("_int2str",196).
isEscape("_flt2str",197).
isEscape("_int_format",198).
isEscape("_flt_format",199).
isEscape("_str2flt",200).
isEscape("_str2int",201).
isEscape("_chr_eq",202).
isEscape("_chr_lt",203).
isEscape("_chr_ge",204).
isEscape("_chr_hash",205).
isEscape("_chr_quote",206).
isEscape("_chr_format",207).
isEscape("_str_eq",208).
isEscape("_str_lt",209).
isEscape("_str_ge",210).
isEscape("_str_hash",211).
isEscape("_str_len",212).
isEscape("_str_gen",213).
isEscape("_stringOf",214).
isEscape("_explode",215).
isEscape("_implode",216).
isEscape("_str_find",217).
isEscape("_sub_str",218).
isEscape("_str_split",219).
isEscape("_str_concat",220).
isEscape("_str_reverse",221).
isEscape("_str_start",222).
isEscape("_str_splice",223).
isEscape("_str_multicat",224).
isEscape("_str_hdtl",225).
isEscape("_str_back",226).
isEscape("_str_cons",227).
isEscape("_code2str",228).
isEscape("_str_apnd",229).
isEscape("_str_quote",230).
isEscape("_str_format",231).
isEscape("_getenv",232).
isEscape("_setenv",233).
isEscape("_envir",234).
isEscape("_getlogin",235).
isEscape("_fork",236).
isEscape("_thread",237).
isEscape("_kill",238).
isEscape("_thread_state",239).
isEscape("_waitfor",240).
isEscape("_shell",241).
isEscape("_newLock",242).
isEscape("_acquireLock",243).
isEscape("_waitLock",244).
isEscape("_releaseLock",245).
isEscape("_ins_debug",246).
isEscape("_stackTrace",247).
