= Why Star?

Star is first of all a general purpose programming language. You can
use it to effectively solve problems in many domains. Star was
originally developed to help write analytical and statistical
applications. However, it has evolved into a general purpose
problem-oriented programming language.footnote:[As opposed to a
systems-oriented programming language like C.] Many of the features
and functionalities of the platform are expressed in a way that is
consistent with Star. As such, it plays a key role in enabling the
different elements of an application built on the platform to work
smoothly together.

== Functional First

Star is a '`functional-first`' programming language. What this means is
that Star makes it easier and more natural to write in a functional
style.

=== Verbs as well as Nouns

Object oriented languages have a very finely developed sense of the
noun. An object is intrinsically a noun; objects reference concrete or
abstract things that a programmer is manipulating. The notation of
classes, interfaces, inheritance and so on represents a powerful set
of concepts for organizing the application's nouns.

However, just as in spoken languages like English, verbs are also
important: what you do with objects is at least as important as the
objects themselves. Most OO languages do not treat verbs --
a.k.a. methods – with the same respect that they confer on nouns.

The result is that methods are written using a vocabulary that a
programmer in the 1970's would be completely familiar with – even when
the same programmer would find classes and interfaces novel concepts.

Functional languages give more weight to the verbs. A function is a
first class value and there are many ways in which functions can be
combined and abstracted. The result is that the expression of control
in a functional language can be subtler and more expressive than is
possible in most OO languages. This makes a material difference to the
productivity of the programmer and can also make a difference in the
readability of the code.

== Asynchronous Code

Many modern software environments are better suited to _asynchronous_
computations than _synchronous_ computations. For example, it takes
take for a web browser to download a resource; and it makes for a
better user experience if the application can continue to function
even while waiting for the download to complete.

This is even more true in an Enterprise setting where long-running
transactions are common.

Star has strong coroutining capabilities: with support for yield-style
generators, asynchronous programming and green threads. This
simplifies the design of reactive applications and allows long-running
transactions to be modeled.

== Star is Rich

Star is a full-featured language. It is an intentionally rich
language. In addition to the features described here are concurrency
features, data abstraction features that include the concept of
existentially quantified types – that enables abstract data types –
and computation expressions – that are important when designing
systems that rely on being able to delay and control how expressions
are evaluated; and many more.

This is part of a `batteries included` strategy: we can enhance
programmer productivity by including many of the features that they
are likely to need. We can support this strategy by making it more
straightforward to develop those included features in Star.

== A Little Context

The origins of Star lie in a platform that was originally oriented
towards complex event processing applications.<<luckham:2012>>
StarRules — as it was known then — was a rules language that allowed
one to express CEP-style rules succinctly.

However, as often happens, requirements evolved and CEP itself became
just one of many application areas that the Starview platform can
address. The same pressures for generality in the platform lead to a
greater interest in extensibility and generality in the programming
language.

In the chapters that follow, we will focus on three major features of
Star that define much of the essence of Star: actors, contracts and
features that are useful in representing complex information, such as
knowledge representation.
