\input texinfo
@include version.texi
@setfilename thinking.info
@settitle Thinking About Star

@copying
Copyright @copyright{} 2019 and beyond, Francis G. McCabe and Michael Sperber

All rights reserved.
@end copying

@titlepage
@title Thinking about Star
@author Francis G. McCabe
@author Michael Sperber

@page
@insertcopying
@end titlepage

@ifplaintext
@insertcopying
@end ifplaintext

@contents

@node Top
@top Thinking About Star

@include ../macros.texi

Star is a functional, multi-paradigm and extensible programming
language. It is a full-scale language, capable of expressing many
kinds of program. As such it is a rich language with many features.
Star was originally developed as part of a framework for processing a
range of real-time business applications such as factory scheduling
and data analytics.  This white paper explores some of the basic
features of the language and shows by example how it can be used to
solve problems.

@include intro.texi

@include functional.texi

@include contracts.texi

@include knowledge.texi

@include getting.texi

@node References
@unnumbered References

@noindent
[luckham:2012] Luckham, David, @emph{Event Processing for Business:
Organizing the Real-Time Enterprise}, John Wiley & Sons, 2012.

@bye


