\chapter{Date and Time}
\label{dateAndTime}


The format string consists of letters, spaces and other characters; the letters control the representation of some aspect of the date, other non-letter characters are displayed as is in the result. <<tableFormatTbl>> contains the definitions of the available formatting characters.

\begin{table}[h]
\begin{center}
.Date Formatting Control Letters\label{tableFormatTbl}
\begin{tabular}{|llll|}
\hline
Letter&Date Component&Presentation&Examples\\
\hline
\tt G&Era designator&Text&\tt AD\\
\tt y&Year&Year&\tt 1999; 01\\
\tt M&Month in year&Month&\tt July; Jul; 07\\
\tt w&Week in year&Number&\tt 25\\
\tt W&Week in month&Number&\tt 2\\
\tt D&Day in year&Number&\tt 191\\
\tt d&Day in month&Number&\tt 2\\
\tt F&Day of week in month&Number&\tt 1\\
\tt E&Day in week&Text&\tt Tuesday; Tue\\
\tt a&AM/PM&Text&\tt PM\\
\tt H&Hour in day (0-23)&Number&\tt 0\\
\tt k&Hour in day (1-24)&Number&\tt 24\\
\tt h&Hour in day (1-12)&Number&\tt 11\\
\tt m&Minute in hour&Number&\tt 34\\
\tt s&Second in minute&Number&\tt 56\\
\tt S&Millisecond in second&Number&\tt 543\\
\tt z&General time zone&Text&\tt PDT; GMT-08:00\\
\tt Z&RFC 822 time zone&Text&\tt -0800\\
\hline
\end{tabular}
\end{center}
\end{table}

The `\_format` function may be invoked implicitly in a string <<Interpolation>> expression. For example, the expression:
[listing]
"\$(now()):dd-MMM-yyyy hh:mm:ss;"

is equivalent to the expression:
[listing]
\_format(now(),"dd-MMM-yyyy hh:mm:ss")

\begin{aside}
This makes more of a difference when combined with other formatting and displaying, as in:
[listing]
logMsg(info,"Balance on \$(today()):dd-MMM-yy; is \euro\$Amnt:9,999.00;");

which will result in a line of the form:
[listing]
Balance on 24-Mar-13 is \euro{}23.56

being displayed.
\end{aside}

==== Repeated Date Formatting Control Characters
The repeated pattern control characters sometimes change their meaning when repeated:
\begin{description}
Text:: If the control character is repeated 4 or more times then the _long_ form of display is used when appropriate. Otherwise a short form is used.
Year:: If the control character is repeated 2 times -- i.e., if `yy` is used as the year format -- then the year is truncated to two digits. Otherwise, the year is printed in full.
Month:: If the `M` control is repeated 3 or more times then the text name of the month is used; (full name for 4 or more repetitions, short name for 3 repetitions). Otherwise, a numeric number is displayed.
Number:: The numeric value is displayed, with zero padding to ensure at least as many digits as format control characters.
\end{description}

\subsection{`parse\_date` -- Parse a `string` as a `date`}
\label{parseDate}
\index{date!formatting}
\index{parse a date string}

[listing]
parse\_date has type (string,string)=>date;


The `parse\_date` function parses a `string` into a `date` value. The first argument is the `string` to parse, the second is a format control string used to guide the parsing of the date. The form of the format control string is the same as for `format\_date` (see <<formatDate>>).

If the string cannot be parsed as a valid date using the control string, then the value returned is `never`.


\subsection{`timeDiff` -- Compute difference between two `date`s}
\label{timeDiff}
\index{date!difference between two dates}

[listing]
timeDiff has type (date,date)=>long


The `timeDiff` function `subtracts' one `date` from another returning the difference as a number of milliseconds.

\subsection{`timeDelta` -- Apply a delta to a `date`}
\label{timeDelta}
\index{date!add delta to a date}

[listing]
timeDelta has type (date,long)=>date

The `timeDelta` function adds an increment to a `date` -- expressed as a number of milliseconds -- and returns a new `date`.
\begin{aside}
The increment may be negative; for example, to compute yesterday's `date`, the following expression suffices:
[listing]
timeDelta(today(),-86400000L)

\end{aside}
