= Date and Time

Date and time support revolves around the `time` built-in type.

== The `time` Type

The `time` type is a structure that refers to Unix time: i.e.,
the number of seconds since January 1st, 1970 GMT:

[source,star]
----
public time ::= .time(float). -- Time since 1st Jan 1970
----

The underlying representation of time values is `float`; this
allows us to represent time values that are a fractional number of
seconds. However, the actual precision of time values depends on the
operating system; typically we expect at least microsecond precision.

== Date and Time Functions

===  `now()`

The `now` function returns a `time` value that denotes the
current wall clock time:

[source,star]
----
now: () => time
----

===  `today()`

The `today` function returns a `time` value that denotes the
wall clock time at midnight this morning:

[source,star]
----
today: () => time
----

===  `ticks()`

[source,star]
----
ticks: () => integer
----

The `ticks` function returns an integer that denotes the number
of micro seconds since the invokation of star program. This number is
not intended to be a reliable measure; in particular it will 'roll
over' every 73117 years.

== Implemented Contracts

===  The `equality` contract

===  The `comp` contract

===  The `display` contract

Times are displayed according to the standard format:

[source,star]
----
www dd/mmm/yyyy hh:MM:SS aa
----

=== The `format` contract

The `_format` function computes a readable string representation of a
`time` as a string displaying the date and/or time. The second
argument is a format string that guides how to format the string.

The format string consists of letters, spaces and other characters;
the letters control the representation of some aspect of the date,
other non-letter characters are displayed as is in the
result.

The `_format` function is typically used inside an interpolated string. For example:
[source,star]
----
"$(today()):yyyy-mmm-ddd;"
----
shows the current date in the format @emph{year}-@emph{mon}-@emph{day}.

[cols="1,10"]
|===
| `G` 
a| The `G` code signifies the era; i.e., whether the year is before
the year zero or not. Years that are before year zero are designated
`BCE` (before common era) and later years are designated
`CE` (common era).

This is a repeated code, with 1 through 3 repetitions valid.

| `y` 
a| The `y` code signifies the year.

This is a repeated code, with 1 through 4 repetitions valid. For example,

[source,star]
----
_format(today(),"yy")
----
displays the least significant two digits of the year; and

[source,star]
----
"$(today()):yyyy;"
----
shows the full 4 digit year.

| `m` 
a| The `m` code signifies the month. This is a repeated code, with minimum 2 repitions.

If the code `m` or `mm` is used then the month is displayed
as a decimal number in the range 1-12, with `1` denoting January,
and 12 denoting December.

If the code `mmm` is used, then the month is written using the
three letter abbreviation (for example, `Jun` denoting June.

For a higher number of repetitions, the full name of the month is
printed. Note though that a minimum of nine repetitions is needed to
avoid truncating a month name.

|  `w` 
a| The `w` code signifies the day of the week. This is a repeated code, with minimum 1 repetition.

If the code `w` is used, then the day of the week is displayed as
a digit, with Sunday referred to as 0.

If the code `ww` or `www` is used then the day of the week
is displayed using a three letter abbreviation.

If more repetitions are used then the long form of the day of the week
is used. Although, in order to avoid truncating a week day name, there
should be eight repetitions.

For example, if it is Friday today, then
[source,star]
----
_format(now(),"www")
----
results in 
[source,star]
----
"Fri"
----
whereas
[source,star]
----
"$(now()):wwwwwwww;"
----
would result in
[source,star]
----
"  Friday"
----

| `D`
a| The `D` code signifies the day of the year, in the range 1-366.

This is a repeated code, one should use `DDD` to ensure displaying all the days in the year.

| `d`
a| The `d` code signifies the day of the current month, in the range 1-31.

This is a repeated code, one should use `dd` to ensure displaying all the days in any month.

| `H`
a| The `H` code signifies the hour, in the range 0-23. I.e., the
hour is displayed in maritime fashion, with 00 denoting midnight and
17 denoting 5 pm.

This is a repeated code, one should use `HH` to ensure displaying all the hours in the day.

| `h`
a| The `h` code signifies the hour, in the range 0-11, the number of
hours since midnight or noon.

This is a repeated code, one should use `hh` to ensure displaying all the hours in the day.

@quotation Note
It is recommended to also use the `a` or `A` codes to indicate AM or PM.
@end quotation

| `M`
a| The `M` code signifies the number of minutes since the top of the hour; in the range 0-59.

| `S`
a| The `S` code signifies the number of seconds since the beginning
of the current minute; in the range 0-59.

| `a`, `A`

a| The `a` and `A` codes are used to designate whether a time
is before noon or after. Use `a` to show `am` or `pm`
and use `A` to show `AM` or `PM` respectively.

This is a repeated code, one should use `aa` or `AA`.

| `z`
| The `z` code is used to show a string indicating the time zone associated with the time.

| `Z`
a| The `Z` code is used to show the time zone in standard numeric format.

This is a repeated code, the valid forms are 3, 5 and 6 repetitions:

* If `ZZZ` is used, then the time zone shows the number of hours
since UTC, e.g., pacific standard time is -08 hours.
* If code `ZZZZZ` is used, then the time zone shows the number of
hours and minutes in the format +HHMM.
* If code `ZZZZZZ` is used, then the time zone shows the number of
hours and minutes in the format +HH:MM.

| Others
| Any other characters in a time format string are displayed as is. This allows the use of characters such as `-` to separate fragments of a date and `:` to separate time segments.

|===

== Other time related functions

=== `timeDiff` -- the difference between two times

[source,star]
----
timeDiff:(time,time) => float
----

The `timeDiff` returns the difference between two times -- expressed as a floating point number of seconds.

=== `timeDelta` -- increment a time

[source,star]
----
timeDelta:(time,float) => time
----

The `timeDelta` function adds a number of seconds to a `time` value to obtain a
new `time`. For example, to get the `time` corresponding to yesterday we can do:

[source,star]
----
yesterday() => timeDelta(today(),-86400000.0)
----

===  `parseTime` -- parse a time

The `parseTime` function parses a string using a format string as
guidance for the format of the date/time.

[source,star]
----
parseTime:(string,string)=>option[time]
----

The first argument is the string to parse, the second is a format string as defined above.

For example, if we have a date string produced:
[source,star]
----
Td = _format(today(),"yyyy-mm-dd")
----
we can parse the result using the same format:
[source,star]
----
parseTime(Td,"yyyy-mm-dd")
----

Since parsing is not guaranteed (the date/time may not be parseable
using the guiding format string) the return type from `parseTime`
is `option`al.
