@node Grammar Rules
@chapter Grammar Rules
@cindex grammar rules

There are many occasions when it is necessary to parse text. For
example, the @Star{} run-time has parses for URIs, json files as well
as for some internal formats.

The grammar rule notation is intended to make it straightforward to
develop parsers using a high level notation.

@node Grammar rule notation
@section Grammar rule notation

@float BNF,grammarRuleFig
@caption{Grammar Rule Notation}
@display
@anchored{Grammar Rule} ::= @refer{GrammarRuleHead} @code{-->} @refer{RuleBody}

@anchored{GrammarRuleHead} ::= @refer{NonTerminal} @code{>>} @refer{Expression}

@anchored{Terminal} ::= @code{[} @refer{Pattern} @code{,}@dots{}@code{,} @refer{Pattern} @code{]}

@anchored{NonTerminal} ::= @refer{Identifier} | @refer{RuleHead}

@anchored{RuleBody} ::= @refer{NonTerminal} |
  @refer{Terminal} |
  @refer{RuleBody} @code{,} @refer{RuleBody} |
  @refer{RuleBody} @code{|} @refer{RuleBody} |
  @refer{RuleBody} @code{*} |
  @refer{RuleBody} @code{*} @refer{RuleBody} |
  @code{~} @refer{RuleBody} |
  @refer{RuleBody} @code{>>} @refer{Pattern} |
  @code{@{} @refer{Condition} @code{@}}


@end display
@end float


