%!TEX root = reference.tex
= Macro Language
[[MacroLanguage]]
The macro language supports the rewriting of parse tree structures -- prior to type checking.
\begin{aside}
The fact that macro processing applies before type checking implies that it is both possible and required to translate non-native *Star* program fragments into *Star* programming constructs.
\end{aside}

\begin{aside}
As a result it is not possible to use the macro  language to construct a program expression that is unparsable -- although it may not be compilable.
\end{aside}

There are two variants of macro program -- macro rules and macro functions.
A macro rule is a rule that applies to a fragment of the text of the program itself. A macro function is a regular *Star* function whose type signature is
[listing]
(quoted)=>quoted


Macro rules take the form:
\begin{figure}[htbp]
\begin{eqnarray*}
[[MacroRule]]MacroRule::=`\#`<<MacroPattern>>\ `==>`\ <<MacroReplace>>\\
&nbsp;&nbsp;| `\#` `fun` <<Equation>>\\
\end{eqnarray*}
.Macro Rule
[[macroRuleFig]]
\end{figure}

\noindent
where <<MacroPattern>> is a pattern that is applied to abstract syntax tree fragments and <<MacroReplace>> is a replacement template. The macro pattern can bind macro variables, check for literals, and even search within the term. The <<MacroReplace>> is generally a template term that may have variables which can be instantiated by the variables from the pattern.

\begin{aside}
We use the term `fragment of text' here somewhat carefully. All macro patterns can only match syntactically valid subsections of source text. A macro pattern denotes a match on the abstract syntax tree of a source program, not a match on textual source.
\end{aside}

== Macro Patterns
Macro rules are written using the same operators that `regular' programs use. A macro pattern of the form:
[listing]
# ?A+?B ==> ...

is, in fact, more or less the same as the macro pattern
[listing]
# plus(?A,?B) ==>

but for the fact that `+` is a binary operator and is written in infix form. Of course, `+` is not the same symbol as `plus`; but the pattern `?A+?B` is equivalent to:
[listing]
# #(+)#(?A,?B) ==> ...

See <<macroParentheses>>. In effect,  macro patterns are not sensitive to operator declarations.

\begin{figure}[htbp]
\begin{eqnarray*}
[[MacroPattern]]MacroPattern::=<<Identifier>>\ |\ <<String>>\ |\ <<Integer>>\ |\ <<FloatingPoint>>\ |\ <<CharRef>>\\
&nbsp;&nbsp;| `integer`\ |\ `long`\ |\ `float`\ |\ `decimal`\\
&nbsp;&nbsp;| `identifier`\  |\ `string`\\
&nbsp;&nbsp;| <<MacroPattern>>`(`<<MacroPattern>>\sequence{,}<<MacroPattern>>`)`\\
&nbsp;&nbsp;| <<MacroPattern>>`\{`<<MacroPattern>>\sequence{,}<<MacroPattern>>`\`}\\
&nbsp;&nbsp;| <<MacroPattern>>\ `@`\ <<MacroPattern>>\\
&nbsp;&nbsp;| <<MacroPattern>>\ `@@`\ <<MacroPattern>>\\
&nbsp;&nbsp;| [\ <<MacroPattern>>\ ]\ `?`\ <<Identifier>>\\
&nbsp;&nbsp;| `?`<<Identifier>>`./`<<MacroPattern>>\\
&nbsp;&nbsp;| `\#(`<<MacroPattern>>`)\#`
\end{eqnarray*}
.Macro Patterns
[[macroPatternFig]]
\end{figure}

=== Literal Macro Patterns
[[literalMacroPtn]]
(((macro,pattern!literal)))
Literal identifiers, numbers and strings may act as macro patterns.

A literal number or string matches exactly the same literal value in the abstract syntax tree.
\begin{aside}
Identifiers may act as literal patterns -- provided that they have not previously been marked as a macro variable. If an <<Identifier>> is declared as a macro variable then an occurrence of the variable acts as a test for equality.
\end{aside}
\begin{aside}
A literal number or string _may not_ be the sole pattern of a <<MacroRule>>. I.e., a <<MacroRule>> of the form:
[listing]
# 34 ==> 56

is not legal.
\end{aside}

=== Macro Variable Pattern
A pattern of the form
[listing]
?Var

will match any structure and bind the macro variable `Var` to that structure. If there is more than one occurrence of the macro variable then they must all have the same value. For example, the following macro replaces a redundant sum with a multiplication:
[listing]
#?X + ?X ==> 2*X.

A second variation of the macro variable pattern allows any macro pattern to be applied and the matched result to be bound to a variable:
[listing]
\#(_Ptn_)\#?_Var_

\begin{aside}
The parentheses are good practice: the priority of `?` as an infix operator is 100, which means that most operator expressions will require the parentheses.
\end{aside}

Subsequent references to a macro variable, including on the _right hand side_ of a macro rule do not require the `?` prefix.

=== Application Macro Pattern
[[applicMacroPtn]]
(((macro,pattern|application)))

An `applicative pattern' -- i.e., a pattern that resembles a function call -- matches abstract syntax terms that are similarly applicative. For example, the pattern in the macro rule:
[listing]
\# foo(?X,?Y) ==> bar(Y,X)

will match abstract syntax terms that consist of the identifier `foo` applied to two arguments.
\begin{aside}
This rule will _not_ match `foo` terms involving 0 or 1 arguments, nor more than 2 arguments.
\end{aside}
\begin{aside}
The application macro pattern actually applies (sic) to _any_ application expression regardless of the use of operators or the role of the application. For example, the rule:
[listing]
\# ?X + ?Y ==> plus(X,Y)

involves the use of the binary operator `+`. However, the operator pattern is equivalent to a rule of the form:
[listing]
\# +(?X,?Y) ==> plus(X,Y)

except that the grammar prohibits operators being used as `regular' functions. The binary `+` rule can, however, be written:
[listing]
\# \#(+)\#(?X,?Y) ==> plus(X,Y)

\end{aside}

\noindent
Other bracket pairs also support analogous application syntax; and the macro patterns to suit. For example, the macro rule:
[listing]
\# A[?Ix] ==> B(Ix)

matches `square bracket terms' such as `A[2]` and `A[foo("alpha")]`; replacing them by `B(2)` and `B(foo("alpha"))` respectively.

The macro rule:
[listing]
\# #(?Op)#[?Ix] ==> \_index(Op,Ix)

is based on the standard macros used to provide the traditional array indexing notation in terms of the standard `indexable` contract (see <<indexableContract>>).

=== Nested Search
The pattern
[listing]
?V./_Ptn_

binds the macro variable _V_ to the term being matched, provided that, within the term being matched there is a sub-expression that matches `_Ptn_`. This pattern is especially useful for useful for transformations that are not locally specifiable. The location of the matched sub-pattern can be referenced in the nested replacement (see <<NestedReplacement>>).

\begin{aside}
The left hand side of the `./` operator _must_ be a macro variable.
\end{aside}

=== Number Patterns
The pattern
[listing]
integer

will match a _literal_ integer in the program.
This pattern will only match numeric literals, it will not match an expression whose value is an integer.
\begin{aside}
This pattern would normally be used in conjunction with a macro variable pattern -- as it is not value specific.
\end{aside}
For example, the pattern
[listing]
integer?V

would bind the macro variable `V` to `12` if matching the literal 12, but would not match
[listing]
6*2

The other numeric patterns `long`, `float` and `decimal` similarly match literals of the appropriate type.

=== Identifier Pattern
The pattern
[listing]
identifier

matches any identifier. Note that the `identifier` pattern will _not_ match any keywords of the language.

=== The `string` Macro Pattern
The `string` macro pattern matches any literal string value.
\begin{aside}
A `string` pattern will not match a string literal that includes any <<StringIterpolation>> expressions. Although it could be used to match parts of such a string literal.
\end{aside}


=== Parentheses
(((macro,parentheses)))
The `normal' parentheses -- `()` -- are _not_ ignored by the parser. I.e., a term of the form:
[listing]
(A+B)

is _not_ the same to the macro processor as the term
[listing]
A+B

Thus the macro rule:
[listing]
# (?X) ==> ...

matches terms that have been enclosed in parentheses, and matches `(A+B)` by binding the macro variable `X` to `A+B`. It does _not_ match `A+B`.

=== Macro Parentheses
[[macroParentheses]]
(((macro,parentheses!macro)))
The macro parentheses -- `\#(...)\#` -- _are_ ignored by the parser. I.e., a term of the form
[listing]
\#(A+B)\#

_is_ syntactically equivalent to `A+B`.

Macro parentheses are used in macro rules for cases where the operator priorities of normal expressions interacts with the priorities of macro rules.

For example, the macro rule:
[listing]
# #(select all from ?P in ?S)# ==> list of \{ for P in S do elemis P \}

uses `\#()\#` parentheses to isolate the `select` pattern being matched within the rule.

Another use for `\#()\#` is in matching the function part of an application. For example, the macro rule pattern
[listing]
... \#(?F)\#(?A1,?A2) ...

matches any binary function application and binds the macro variable `F` to the function part of the application and binds macro variables `A1` and `A2` to the first and second arguments.

\begin{aside}
Note that it is _not_ permitted for a macro variable to be the top-level pattern in a macro rule. The rule:
[listing]
# \#(?F)\#(?A1,?A2) ==> bar(A1,A2)

is not permitted because the top-level operator in the rule is a macro variable -- `?F`. This form of pattern is very useful in sub-patterns of the macro rule.
\end{aside}


=== Applicative Pattern

The macro operator `@@` matches any applicative expression. The left hand sub-pattern matches the operator part of the applicative and the right hand side matches the arguments.

For example, the macro pattern:
[listing]
... ?F@@?A ...

matches any applicative expression -- including expressions involving standard symbols such as `=>` or `is`.

\begin{aside}
The `@@` operator may not be the _most significant_ operator in a macro rule.
\end{aside}




== Macro Replacements
Generally, a macro replacement is simply a fragment of program text with macro variable references embedded where input should be carried over.

\begin{figure}[htbp]
\begin{eqnarray*}
[[MacroReplace]]MacroReplace::=<<Identifier>>\ |\ <<String>>\ |\ <<Integer>>\ |\ <<FloatingPoint>>\ |\ <<CharRef>>\\
&nbsp;&nbsp;| <<MacroReplace>>`(`<<MacroReplace>>\sequence{,}<<MacroReplace>>`)`\\
&nbsp;&nbsp;| <<MacroReplace>>`\{`<<MacroReplace>>\sequence{,}<<MacroReplace>>`\`}\\
&nbsp;&nbsp;| <<MacroReplace>>\ `@@`\ <<MacroReplace>>\\
&nbsp;&nbsp;| `?`\ <<Identifier>>\\
&nbsp;&nbsp;| <<Identifier>>`./`<<MacroReplace>>\\
&nbsp;&nbsp;| `\#(`<<MacroReplace>>`)\#`\\
&nbsp;&nbsp;| <<MacroReplace>> `\#\#` `\{` <<MacroRule>> \sequence{;}<<MacroRule>> `\`}
\end{eqnarray*}
.Macro Replacement Terms
[[macroReplaceFig]]
\end{figure}


=== Macro Variable
An occurrence of a macro variable in the replacement pattern is replaced by the fragment of program that was matched by the corresponding macro variable pattern. For example,
[listing]
# foo(?X) ==> bar(X)

replaces occurrences of the form
[listing]
foo(\{a="alpha"\})

with
[listing]
bar(\{a="alpha"\})


=== Nested Replacement
[[NestedReplacement]]
A replacement expression of the form:
[listing]
?V./_Rep_

can be used to replace a nested sub-expression that was matched by a `./` pattern. The replacement text consists of the whole of the expression matched -- held as the value of the variable `?V` -- except that the part of the original that had been matched by the nested pattern is replaced by `_Rep_`.

=== Generated Symbols
(((macro,generated symbol)))
The macro replacement pattern
[listing]
#\$ _ident_

results in a new identifier of the form
[listing]
_ident1234_

where the number that is added to the `_ident_` argument of `\#\$` is guaranteed to be unique within a single compilation _and_ that multiple occurrences of `\#\$_ident_` within a single macro rule will be replaced by the _same_ identifier.

This is useful for macros that generate new symbols. For example, the macro rule:
[listing]
#unfold(?Ex./Ave(?Tm)) ==> let\{#\$ave=Average(Tm)\} in Ex./#$ave;

would have the effect of `lifting' a call to the `Ave` function and making it into a `let` expression. I.e., it would rewrite
[listing]
10+Ave(foo(X))

to
[listing]
let\{ ave34=Average(foo(X))\} in 10+ave34


=== Interned Strings
(((macro,interning string as symbol)))
The macro replacement expression:
[listing]
#\tlda _Exp_

where _Exp_ is a `string`-valued _macro expression_ is replaced by an identifier whose name is the string value of _Exp_.

For example, the macro rule:
[listing]
#applyOf(?Exp) ==> #\tlda("Apply"#+Exp)

can be used to construct an identifier whose prefix is `Apply`. The variable assigned to in:
[listing]
var applyOf(2) := 34

is `Apply2`.

=== Location
[[locationMacro]]
(((macro,location)))

The replacement pattern
[listing]
#__location__

is replaced by a string that denotes the location of the original term that was matched by this macro rule.

Typically this string indicates the file name and the line number of the term.

=== Macro Let
[[ScopedMacros]]
A replacement pattern of the form:
[listing]
_Rep_ ## \{ <<MacroRule>>\sequence{;}<<MacroRule>> \}

acts as though the replacement were just `_Rep_`. However, in the continued processing of `_Rep_`, there may be additional macro substitution. The locally defined rules take precedence over other rules.

==== Free Variables in Macro Rules
Rules within the sub-scope may reference macro variables defined in outer macro rules. These free variables retain the value that they were given as part of the macro rule pattern matching.

For example, the inner rule in:
[listing]
# foo(?X) ==> bar(given) ## \{
  #given ==> X;
\}

refers to the macro variable `X` that is bound during the match with `foo`. The rule for `given` may reference `X` which is free in the `given` rule but bound by the `foo` rule.

=== Code Macros
[[codeMacros]]
In addition to the macro language defined here, it is also possible to define macro processing rules using `regular' *Star*. So-called code macros are normal *Star* programs whose type is
[listing]
(quoted)=>quoted

Code macros use a prefix `\#` to mark them as being macro functions rather than just being normal functions.

For example, the macro definition:
[listing]
\#glom(?AA,?BB) ==> glue(AA,BB) ## \{
    \#glue(X,Y) is glm(X,Y)

    glm(A,<|()|>) is A
     |  glm(<|()|>,A) is A
     |  glm(<|?L;?R|>,A) is <|?L;?glm(R,A)|>
     |  glm(A,B) is <|?A;?B|>
  \};

is part of the standard macro library that `glues' two macro terms together.
\begin{aside}
The `glom` macro is very useful when generating sequences of definitions for example -- because the generation definitions must be separated by semi-colons.
\end{aside}
Notice that in this example we do not mark the `glm` function with a `\#`. This is because `glm` is an internal function that is not intended to be accessible directly. Only macro code functions that are intended to be accessed directly should be marked as code macros. This allows other functions -- whose type signatures may not make them suitable for macro processing -- to be mixed in with code macros.

Another difference between code macros and normal macro rules is that one has to be explicit about using the quoted form. Furthermore, as above, the programmer has to use the `?` form to de-quote variables in the replacement even when they have been mentioned in the left-hand side.

\begin{aside}
Generally, code macros tend to be `lower-level' than normal macro rules. However, expression evaluation is inherently faster than macro replacement; and the ability to use auxiliary structures -- such as `map`s of program fragments -- during macro processing make code macros preferable in cases where substantial transformations are being implemented.
\end{aside}

== Macro Evaluation
[[macroEvaluation]]
During the macro pattern matching process it is quite possible for multiple macro rules to match a given fragment of source text.
\begin{aside}
The `source text' referred to here is actually an abstract syntax tree -- or part of. Abstract syntax trees have a standard type: `quoted` -- see <<quotedText>>.
\end{aside}

Macro evaluation is an `outside-in' process in which rules are applied in the order that they are written -- with local rules overruling imported rules.

\begin{enumerate}
\item Macro replacement is focused on a so-called `current term' -- the fragment of the abstract syntax tree that is the current candidate for replacement.
\item
The set of available macro rules is used to rewrite the current term. A macro rule is applicable to the current term if its pattern matches the term.
\item
If the applicable macro is a code macro then the code macro function is entered and its return value is used as the replacement.
\item
If there are no applicable macros, then -- in the case of an applicative term -- each of the arguments of the term are rewritten.
\item If any of the arguments are successfully rewritten by a macro-rule, or if a rule applied to the current term as a whole, then the macro process is repeated on the rewritten term.
\end{enumerate}

In more detail, the rules for determining which macros may be applied is governed by the following ordering:
\begin{enumerate}
\item
Within a scoped macro -- see <<ScopedMacros>> -- macro rules that are defined within the sub-scope take precedence over other macro rules.
\item
Any macros that are defined at the top-level of a package.
\item
Macros that are part of imported packages.
\item
Macro rules that are defined earlier in a given scope take precedence over rules defined later in the scope.
\end{enumerate}

=== The Most Significant Macro Operator
[[mostSignificant]]
(((macro,most significant operator)))
In any given macro pattern, there is a _most significant operator_ that represents the outermost symbol of the terms that the pattern matches.

For a simple pattern such as `integer`, or simply `34`, the pattern itself is the most significant operator.

For a compound pattern, such as `foo(?A1,?A2)` the most significant operator of the function part of the pattern is the most significant operator (in this case it is the literal identifier `foo`.

The macro language imposes a restriction on macro rules -- the most significant operator of the pattern on the left hand side of the rule _must_ be a literal identifier pattern.
