%!TEX root = reference.tex
= Associative Dictionaries
[[associativeMap]]

(((expressions,associative dictionary)))
(((associative dictionary expression)))
Dictionaries allow the programmer to establish an associative mapping between pairs of elements. They are convenient when it is not known what the actual elements of the association will be at design time.

\begin{aside}
An important property of dictionaries is that there can be at most _one_ value associated with a given key. This is one of the primary differences between dictionaries and lists.
\end{aside}

== Dictionary Type
[[mapTypes]]
(((type,dictionary`dictionary` type)))

The `dictionary` type takes the form of a type expression with two type arguments: the type of the key and the type of the value.
\begin{figure}[htbp]
\begin{eqnarray*}
_Type_&\arrowplus&`dictionary of (`_Type_`,`_Type_`)`
\end{eqnarray*}
.Dictionary Type
[[mapTypeFig]]
\end{figure}
In a `dictionary`, every key must have the same type; as must each value in the `dictionary` -- although the keys' type may be different to the values' type.

For example, the type expression:
[listing]
dictionary of (string,integer)

denotes the type of a dictionary whose keys are `string`s and whose values are `integer`s.

The `dictionary` type's structure is not public. It is defined as though by a <<KindAnnotation>>:
[listing]
dictionary has kind type of (type,type)

\begin{aside}
In addition, there is a constraint on the types of keys: they must implement the `equality` contract. This means that it is not possible to use as keys any value that contains a program value. There is no such restriction on the values -- it is quite possible to have a map from `string`s to functions (say).
\end{aside}


== Dictionary Literals
[[mapLiteral]]
(((dictionary,literal)))
(((dictionary literal@`dictionary` literal)))
(((dictionarys)))
A `dictionary` literal consists of a `dictionary` brace term with each element in the dictionary represented as a pair
[listing]
_Key_ -> _Value_

<<mapLiteralFig>> defines the syntax of dictionary literals.
\begin{figure}[htbp]
\begin{eqnarray*}
_Expression_&\arrowplus&`dictionary of ``[`_MapElement_\sequence{,}_MapElement_`]`\\
_MapElement_::=_Expression_\ `->`\ _Expression_
\end{eqnarray*}
.Dictionary Literal
[[mapLiteralFig]]
\end{figure}
For example,
[listing]
dictionary of ["alpha" -> 1, "beta"->2]

is a dictionary consisting of `string` keys to `integer` literals.
An associative `dictionary` literal may not have more than one value associated with any given key.

An empty `dictionary` literal is written:
[listing]
dictionary of []


\begin{aside}
There is no _pattern_ form of a `dictionary` literal: it is not possible to pattern match against a dictionary. However, it is possible to constrain an equation based on a dictionary argument -- using semantic guard:
[listing]
keyPresent(Ky,D) where present D[Ky] is D[Ky];

\end{aside}


== Accessing Elements of a Dictionary
[[associativeMapAccess]]
(((dictionary,accessing elements)))
(((expressions,access elements of dictionary)))

There are implementations of the `indexable` (see Program~\vref{indexableContractDef}), `sizeable` (see Program~\vref{sizeableContract}), `iterable` (see Program~\vref{iterateContractProg}) and `pPrint` contracts (see Program~\vref{ppContractProg}). Thus, the standard notations for accessing indexed elements, and iterating over collects, apply to `dictionary` values also.

Note that the related contracts `sequence` (see Program~\vref{sequenceContractDef}), `sliceable` (see Program~\vref{sliceableContractProg}) are _not_ implemented for `dictionary` values. In the former case the reason is that `dictionary`s are not naturally accessed in a sequential manner, and in the latter case the _key_s used to access `dictionary`s are not limited to `integer`s.

=== `\_index` -- Index Element
[[indexMapFunction]]
(((indexable contract@`indexable` contract,_index@`\_index`)))
The `\_index` function, which is part of the `indexable` contract (see Program~\vref{indexableContractDef}), is used to access elements of a dictionary -- by providing a key.
[listing]
_index has type for all k,v such that (dictionary of (k,v),k)=>option of v
                where equality over k

\begin{aside}
The type of the index is obtained from the `dictionary` type itself: it is the first type argument.
\end{aside}

\begin{aside}
The `\_index` function requires that `equality` is implemented for the key type.
\end{aside}

\noindent
The `\_index` function has special syntax which is reminiscent of array index expressions:
[listing]
C[Ky]

is equivalent to the expression
[listing]
\_index(C,Ky)

For example, given a dictionary:
[listing]
M is dictionary of [ "alpha"->1, "beta"->2 ]

we can access the value associated with the key `"alpha"` using:
[listing]
M["alpha"]

Since the values accessed from a `dictionary` are always `option`al, we can unwrap them conditionally using a `has value` condition (see <<hasValueCond>>):
[listing]
get(Key) where M[Key] has value V is V


=== `\_set\_indexed` -- Replace Element of Map
[[mapReplaceFunction]]
(((indexable contract@`indexable` contract,_set_indexed@`\_set\_indexed`)))
(((replace element in collection)))
The `\_set\_indexed` function, which is part of the `indexable` contract, is used to set an element in a `dictionary`.
[listing]
\_set\_indexed has type for all k,v such that
                        (dictionary of (k,v),k,v)=>dictionary of (k,v)
                        where equality over k

The `\_set\_indexed` function returns a `dictionary` in which an element is replaced. If the element as _not_ there beforehand, the `dictionary` is augmented with the new key/value pair. If there was an element with the same key, then the value associated with key is replaced.

The `\_set\_indexed` function has special action syntax which is reminiscent of array update actions:
[listing]
C[Ky] := E

is equivalent to the action
[listing]
C := \_set\_indexed(C,Ky,E)

For example, given the variable declaration:
[listing]
var M := dictionary of [ "alpha"->1, "beta"->2 ]

we can add a new key associated with `"gamma"` using the action:
[listing]
M["gamma"] := 3

which is equivalent to:
[listing]
M := _set_indexed(M,"gamma",3)

The `\_set\_indexed` function also has an expression form. The assignment above may also be written:
[listing]
M := M["gamma"->3]


\begin{aside}
As with other forms of update action, the `\_set\_indexed` function does not side-effect the previous value that was bound to the dictionary variable.
\end{aside}

=== `\_delete\_indexed` -- Remove Element from Map
[[mapDeleteFunction]]
(((indexable contractt@`indexable` contract,_delete_indexed@`\_delete\_indexed`)))
(((remove element from collection)))
`\_delete\_indexed` is part of the `indexable` contract -- see Program~\vref{indexableContractDef}.
[listing]
\_delete\_indexed has type for all k,v such that
                           (dictionary of (k,v),k)=>dictionary of (k,v)
                           where equality over k

The `\_delete\_indexed` function is used to remove an element from a dictionary. The `\_delete\_indexed` function returns a new `dictionary` with the identified element removed. The element to delete is identified by its key, not by the kay/value pair.

The `\_delete\_indexed` function has special action syntax which is reminiscent of array update actions:
[listing]
remove C[Ky]

is equivalent to the action
[listing]
C := C[without Ky]

which, in turn, is equivalent to:
[listing]
C := \_delete\_indexed(C,Ky)

For example, given the `var`-declared variable `M` above, we can remove the entry associated with `"alpha"` using:
[listing]
remove M["alpha"]


The `expression variant' of the `remove` notation -- `C[without ky]` -- is more pleasant for functional programs where the dictionary is not held in an updateable variable.

=== Searching a Dictionary
[[searchMap]]
(((dictionary expression,membership predicate)))

A `dictionary` may be searched within a condition using the <<IndexedSearch>> condition.

There are two primary situations for searching an associative `dictionary`: if the _Key_ part of a <<IndexedSearch>> operator is either a literal or is a previously bound variable then there is at most one way of satisfying a <<IndexedSearch>> condition. On the other hand, if the _Key_ is a pattern containing unbound variables then a <<IndexedSearch>> involves iterating over the entire dictionary looking for entries that match the condition.


== Standard `dictionary` Functions
[[standardMap]]

The `dictionary` type implements the standard `sizeable` contract -- see Program~\vref{sizeableContract}. As such, the functions `size` and `empty` are defined for `dictionary` values.

=== `size` -- length of a dictionary
[[sizeMapFunction]]
(((size function@`size` function)))
`size` is part of the `sizeable` contract.
[listing]
size has type for all k,v such that (dictionary of (k,v))=>integer


The `size` function returns the length of its `dictionary` argument; i.e., the number of elements in the `dictionary`.


=== `isEmpty` -- test for empty dictionary
[[emptyMapFunction]]
(((isEmpty function@`isEmpty` function)))
`empty` is part of the `sizeable` contract.
[listing]
isEmpty has type for all k,v such that (dictionary of (k,v))=>boolean


The `isEmpty` function returns `true` if its argument has no elements.
