= Numbers

(((expressions,arithmetic)))
The basis of arithmetic expressions are several contracts: the
`arith` contract which provides definitions of the familiar
_calculator_ functions of `+`, `-`, `*` and
`/`.

In addition, there is an extended set of mathematical functions for
trigonometry, bit string manipulation and so on.

== Numeric Types

There are three standard numeric types: `integer`, `bigint` and `float`.

[#integerType]
=== Integer Type

Integers are 62 bits in precision. However, there are also arbitrary
precision integers if needed.

NOTE: The restriction to 62 bits facilitates improved space representation
in the engine. If more precision is required, arbitrary precision
arithmetic is a good choice.

[#bigintType]
=== Arbitrary Precision Integers

As the name suggests, `bigint` numbers have no fixed
precision. They can be used to represent large values -- up to the
limits of available memory.

NOTE: Operations on `bigint` numbers may be significantly more
expensive than operations on fixed size integers.

In addition, the range of operators supported for `bigint`
numbers is smaller than that for `integer` values.

[#floatType]
=== Float Type

Floating point numbers are based on IEEE 754 double values. However, we
lose 2 bits of precision in comparison.

== Implemented Arithmetic Contracts
(((contract, implemented for `integer` and `float`)))

=== Arithmetic for Integers

The `arith` contract is implemented for `integer`
values (see <<arithContract>>).

=== Arithmetic for Floating Points

=== Display for `integer`

=== Format for `integer`

The format string for `integer` values determines how the number is
formatted. For example, the result of
[source,star]
----
"--$(-15):-   0;--"
----
is
[source,star]
----
"--  -15--"
----

The grammar for legal formatting codes for integral values may be
given in the regular expression:
[source,star]
----
[P+-]?([09 ,.])+[P+-]
----

I.e., a sign specification, followed by digit specifications
optionally mixed with thousands markers and periods, terminated by an
optional sign specification.

The complete formatting codes for formatting numeric values are:

[cols="1,10"]
|===
| `9`
| A digit is displayed if it is significant. I.e., if it is non-zero
or there is a non-zero digit to the left of the digit.

| `0`
a| A zero character is used for numeric values. It always results in a
digit being displayed. For example, the value of
[source,star]
----
"--$(5):00;--"
----
is the string
[source,star]
----
"--05--"
----

| space
a| A space character is similar to the `0` code; except that a
leading space is displayed instead of a leading zero.

For example, the value of
[source,star]
----
"--$(5): 0;--"
----
is the string
[source,star]
----
"-- 5--"
----

NOTE: Signs are treated specially with the space code: any produced sign
character is migrated past leading spaces -- with the result that the
sign character is always abutted to the digits.
For example, the result of
[source,star]
----
"--$(-15):-   0;--"
----
is
[source,star]
----
"--  -15--"
----
The space code is especially useful for lining up columns of figures
where a leading space is preferred over leading zeroes.

| `.`
| A period is displayed if there is a digit to the left.

This is used for showing currency values -- when they are represented
internally as pennies but should be displayed as dollar values -- and
for floating point numbers.

| `,`
a| A comma is displayed if there is a digit to the left.

This is used for displaying values in the _thousands_
notation. For example, the value of
[source,star]
----
"--$(120345567):999,999,999,999;--"
----
is the string:
[source,star]
----
"--120,345,567--"
----
| `-`
a| Is used to control how signed values are presented. If the value is negative then a `-` character is displayed; if the value is positive then a space is displayed.

NOTE: The `-` format code may appear at either end of the display. A
leading `-` results in the sign being displayed at the beginning
-- before any digits -- and a trailing `-` results in the sign
appended to the end.
WARNING: If no _sign_ code is present in the format specification then
nothing is displayed if the value is positive or negative.

| `+`
a| Always results in a sign being displayed. If the value is negative
then a `-` character is displayed; otherwise a `+` character
is displayed.

Like the `-` code, the `+` may appear at either end of the
display format.

| `P`
a| The `P` code uses parentheses on either end of the value to
indicate a negative value. If the value is positive then spaces are
appended to either end; otherwise the number is enclosed in
`()`s.

NOTE: The `P` code should be placed at _both_ ends of the format
specification.  For example, the expression:
[source,star]
----
"Balance: $(Amnt):P999900.00P; remaining"
----
where `Amnt` had value -563 would result in
[source,star]
----
"Balance: (05.63) remaining"
----

| `X`
a| Causes the integer to be formatted as a hexadecimal number; and a
hexadecimal digit is displayed if it is significant. I.e., if it is
non-zero or there is a non-zero digit to the left of the digit.

For example, this can be used to display the Unicode equivalent of a character:
[source,star]
----
"Unicode: $(C)/$(C::integer):XXXXX;"
----
|===

=== Display for `float`

=== Format for `float`

The grammar for legal formatting codes for `float` values is a little more
complex than that for `integer`:
[source,star]
----
[P+-]?[09 ,.]+([eE][+-]?[09 ]+)?[P+-]?
----

I.e., the format string for `float` values permits the exponent
to be printed as well as the mantissa. If the exponent part is missing
and if the `float` value cannot be represented in the available
precision without an exponent then an exception will be thrown.

[#bitString]
== Bit Manipulation Functions

The bit manipulation functions treat `integer` values as 62-bit
bit strings.

===  `.&.` Bit-wise Conjunction
[source,star]
----
(.&.) : (integer,integer)=>integer.
----

The `.&.` operator returns the bit-wise conjunction of two
`integer` values.

===  `.|.` Bit-wise Disjunction
[source,star]
----
(.|.)  : (integer,integer)=>integer.
----

The `.|.` operator returns the bit-wise disjunction of two
`integer` values.

=== `.^.` Bit-wise Exclusive-or
[source,star]
----
(.^.)  : (integer,integer)=>integer.
----

The `.^.` operator returns the bit-wise exclusive of two
`integer` values.

=== `.<<.` Bit-wise Left Shift

[source,star]
----
(.<<.) : (integer,integer)=>integer.
----

The `.<<.` operator left-shifts the left hand argument by the
number of bits indicated in the right argument. It is effectively
multiplication by a power of 2.

=== `.>>.` Bit-wise Arithmetic Right Shift
[source,star]
----
(.>>.) : (integer,integer)=>integer.
----

The `.>>.` operator right-shifts the left hand argument by the
number of bits indicated in the right argument. The most significant
bit is replicated in the shift. It is effectively division by a power
of 2.

=== `.>>>.` Bit-wise Logical Right Shift
[source,star]
----
(.>>>.) : (integer,integer)=>integer.
----

The `.>>>.` operator right-shifts the left hand argument by the
number of bits indicated in the right argument. The most significant
bits of the result are replaced by zero. This operator is sometimes
known as logical right shift.

===  `.~.` Bit-wise Logical Complement
[source,star]
----
(.~.) : (integer)=>integer.
----

The `.~.` operator forms the logical or 1s complement of its argument.

===  `.#.` Bit Count
[source,star]
----
(.#.) : (integer)=>integer.
----

The `.#.` operator computes the number of non-zero bits in its argument.

== Trigonometry Functions

NOTE: All the trig functions assume that the angles that they accept (or
return) are expressed in radians.

===  `sin` -- Sine Function
[source,star]
----
sin : (float) => float.
----

The `sin` function returns the Sine of its argument -- expressed
in radians.

=== `asin` -- Arc Sine Function
[source,star]
----
asin : (float) => float.
----

The `asin` function returns the Arc Sine of its argument --
expressed in radians.

=== `cos` -- Cosine Function
[source,star]
----
cos : (float) => float.
----

The `cos` function returns the cosine of its argument --
expressed in radians.

=== `acos` -- Arc Cosine Function
[source,star]
----
acos : (float) => float.
----

The `acos` function returns the arc cosine of its argument --
expressed in radians.

=== `tan` -- Tangent Function
[source,star]
----
tan : (float) => float.
----

The `tan` function returns the tangent of its argument --
expressed in radians.

=== `atan` -- Arc Tangent Function
[source,star]
----
atan : (float) => float.
----

The `atan` function returns the Arc Tangent of its argument --
expressed in radians.

== Misc Arithmetic Functions

In addition to the standard arithmetic contract (see <<arithContract>>), there
are additional numeric functions:

===  `abs` -- absolute value

[source,star]
----
abs : all t ~~ arith[t],comp[t] |= (t)=>t.
----

The `abs` function returns the absolute value of its argument. It
depends on both teh `arith` and the `comp` contracts, hence
is implemented for both `integer` and `float` values.

=== `max` -- maximum value
[source,star]
----
max: all t ~~ comp[t] |= (t,t)=>t.
----

The `max` function returns the larger of its two arguments.

=== `min` -- minimum value
[source,star]
----
min: all t ~~ comp[t] |= (t,t)=>t.
----

The `min` function returns the smaller of its two arguments. It
is defined on top of the `comp` contract.

=== `sqrt` -- square root
[source,star]
----
sqrt : (float)=>float
----

The `sqrt` function returns the square root of its argument. If
the argument is negative, the returned value is undefined.

===  `ceil` -- ceiling
[source,star]
----
ceil : (float)=>float
----

The `ceil` function returns the nearest integral value that is
equal to or larger than X.

=== `floor` -- floor
[source,star]
----
floor : (float)=>float
----

The `floor` function returns the nearest integral value that is
equal to or smaller than X.

=== `trunc` -- round to closest integral
[source,star]
----
trunc : (float)=>float
----

The `trunc` function returns the nearest integral value to its argument.
NOTE: The value returned by `trunc` is integral, but still of type `float`.

=== `log` -- Natural Logarithm
[source,star]
----
log : (float)=>float
----

The `log` function returns the natural logarithm of its argument.

===  `log10` -- Logarithm Base 10
[source,star]
----
log10 : (float)=>float
----

The `log10` function returns the base 10 logarithm of its argument.

===  `exp` -- Natural Exponentiation
[source,star]
----
exp has type for all t such that (t)=>t where math over t
----

The `exp` function returns the value $e^X$.

=== `random` -- random number generation

(((random number generation)))
[source,star]
----
random : (float)=>float
----

The `random` function returns a number in the half-open range
[0,X) where X is the argument of the function.

The argument of the `random` function must be a positive
number.

The number generated is the next in a sequence of numbers that is
typically pseudo-random: i.e., not actually random but statistically
indistinguishable from random.

=== `**` -- exponentiation
[source,star]
----
(**) : (float,float) => float
----

The `**` function raises the first argument to the power of the second.

For example, the expression
[source,star]
----
X**3.0
----

denotes the cube of `X`.

