%!TEX root = reference.tex
= Concepts and Ontologies
[[ontology]]

Many programs have embedded within them numerous `constant' values that often denote specific concepts. Often these concepts refer to data that the program expects to see in its input at some point, or will produce in its output.

Related to this, an application may need to be _internationalized_ -- that is, be translated for use in different countries by people speaking different languages -- and/or _localized_ -- that is, be programmed to be sensitive to local defaults for things such as how dates are formatted, currencies, and so on.

The `rdf` profile provides facilities for defining _concepts_, _relationships_ between those concepts and _path expressions_ to capture _concept navigation_. In addition, it allows _ontologies_ -- expressed as `N3` files -- to be incorporated into an application.

== RDF and N3
[[rdfN3]]
RDF is a W3C standard for specifying simple ontologies using a very simple language: an RDF graph is a set of _triples_; each triple consists of a subject, a predicate and an object -- all of which are _concepts_. In the standard notation, RDF triples are written using an XML-based notation; however, there is a more convenient notation often used called `N3`.
[listing]
_subject_ _predicate_ _object_.

where `_subject_`, `_predicate_` and `_object_` are all concepts. Such a statement is called a _triple_. N3 supports several shortened forms of triples; for example, a statement such as:
[listing]
person:john family:parent-of person:jim, person:jane.

is equivalent to two triples:
[listing]
person:john family:parent-of person:jim.
person:john family:parent-of person:jim.

and the statement:
[listing]
person:john family:parent-of person:jim;
             dc:has-name "john".

is equivalent to:
[listing]
person:john family:parent-of person:jim.
person:john dc:has-name "john".

The comma allows the same subject and predicate to refer to multiple objects and the semi-colon allows the same subject to have multiple predicate/objects associated with it.

== *Star* Triple Notation
[[n3Notation]]
(((triple notation)))
(((ontology,triples)))
*Star* supports a form of N3 notation together with a path notation that facilitates navigation of concept structures.

However, the exact notation is necessarily different to the standard N3 notation -- the *Star* N3 notation has been `formatted' to fit with the syntactic conventions of the *Star* language. For convenience, we will continue to refer to the *Star* `version' of N3 notation as simply N3SR.

\begin{figure}[htbp]
   \includegraphics[width=0.55\textwidth]{diagrams/n3GraphFig}
   .N3SR Graph Structure
   [[n3GraphFig]]
\end{figure}

\begin{figure}[htbp]
   \includegraphics[width=0.75\textwidth]{diagrams/n3TripleFig}
   .Triple Statement
   [[n3TripleFig]]
\end{figure}

\begin{figure}[htbp]
   \includegraphics[width=0.8\textwidth]{diagrams/n3NounPhraseFig}
   .Noun Phrase
   [[n3NounPhraseFig]]
\end{figure}

\begin{figure}[htbp]
   \includegraphics[width=0.7\textwidth]{diagrams/n3ConceptFig}
   .Concept
   [[n3ConceptFig]]
\end{figure}
