\input texinfo
@include version.texi
@setfilename star.info
@settitle Star Reference @value{VERSION}

@dircategory Programming
@direntry
* star: (star).		Star programming language reference
@end direntry

@copying
Copyright @copyright{} 2019 and beyond, Francis G. McCabe

All rights reserved.
@end copying

@titlepage
@title Star Reference
@author Francis G. McCabe


@page
@insertcopying
@end titlepage

@ifplaintext
@insertcopying
@end ifplaintext

@summarycontents
@contents

@node Top
@top Star Reference

@macro Star
@strong{Star}
@end macro


@ifinfo
@macro turnstile
|-
@end macro
@end ifinfo
@ifnotinfo
@macro turnstile
@U{22a6}
@end macro
@end ifnotinfo

@ifinfo
@macro noteq
!=
@end macro
@end ifinfo
@iftex
@macro noteq
!=
@end macro
@end iftex

@ifnotinfo
@ifnottex
@macro noteq
@U{2260}
@end macro
@end ifnottex
@end ifnotinfo

@macro typeprod{E,Exp,T}
@var{\E\}@turnstile{}\Exp\:\T\
@end macro

@macro anchored{T}
@anchor{\T\}@var{\T\}
@end macro

@noindent
This is the 
@ifinfo
on-line
@end ifinfo 
reference for the @Star{} language, version @value{VERSION}.  
@refill

@noindent
This manual offers an in-depth and complete description of the @Star{}
language. However, it is not a tutorial on the language, and the order
of presentation within the manual reflects that. For a more tutorial
introduction, the reader is referred to @emph{Star Programming} (by
F.G. McCabe).

@menu
* Introduction::
* Lexical Syntax::
* Grammar::
* Well Formed Programs::
* Types::

* Concept index::
* Function index::
* List of Syntax Rules::
@end menu




@include intro.texi

@include lexical.texi

@include grammar.texi

@include wff.texi

@include types.texi

@node Concept index
@unnumbered Concept index
@printindex cp

@node Function index
@unnumbered Standard function index
@printindex fn

@node List of Syntax Rules
@unnumbered List of Syntax Rules
@listoffloats BNF


@bye
