%!TEX root = reference.tex
= Strings
[[strings]]
A string is a sequence of Unicode characters that denotes a fragment of text. This chapter focuses on the built-in functions that are based on the `string` type.

== The Structured String `pP` Type
[[ppType]]
(((pP type)))
(((type,pP@`pP`)))
The `pP` type -- as defined in Program~\vref{ppTypeProg} -- denotes a `structured `string`' value where the structure may be used to represent lines, sub sequences and so on.
\begin{aside}
A primary purpose of the `pP` type is to permit simple formatting policies to be applied after the generation of the displayed form of a value.
\end{aside}

\begin{program}
[listing]
type pP is
     ppStr(string)
  or ppSequence(integer,cons[pP])
  or ppNl
  or ppSpace;

.The Structured String `pP` type[[ppTypeProg]]
\end{program}

The intended semantics of the constructors are:
\begin{description}
`ppStr`:: A literal string. Whenever a literal string is to be generated, the `ppStr` constructor is used to `hold' that string. For example, if the display of a value calls for an opening parenthesis, then the term:
[listing]
ppStr("(")

may be used to denote that.
`ppSequence`::
The `ppSequence` constructor signals a subsequence in the display. It has two arguments: the first is an indentation amount, and the second is a `cons` list[sub]-elements.

The indentation is used if a newline is generated within the subsequence. In that case, the new lines will be indented by the amount requested.
`ppNl`::
Signal a new line in the displayed sequence.
\begin{aside}
Simply signaling a new line does actually imply that a new line will be generated. New lines are generated depending on whether the client of the pretty print requires one in the actual displayed output.
\end{aside}
`ppSpace`::
The `ppSpace` symbol denotes a `line-breakable' space. Multiple `ppSpace`s in sequence are equivalent to a single one.
\end{description}

== The `pPrint` contract
[[pPrintContract]]
(((pPrint contract@`pPrint` contract)))
(((pretty print contract)))

The standard contract `pPrint`, shown in Program~\vref{ppContractProg} together with the `pP` type shown in Program~\vref{ppTypeProg}, is at the core of the standard method for displaying arbitrary values.
\begin{program}
[listing]
contract pPrint over t is {
  ppDisp has type (t)=>pP
};

.The Standard `pPrint` Contract[[ppContractProg]]
\end{program}
The *Star* compiler will automatically generate implementations of the `pPrint` contract for all user-defined types. However, it will not override any implementations defined by the user.
\begin{aside}
It is not guaranteed that _all_ user-introduced types will be detected. In particular, some anonymous types are implicitly introduced by the programmer and these are not guaranteed to be detected.

However, if the compiler cannot find an implementation of `pPrint` then a default implementation will be used.
\end{aside}

The purpose of the `pPrint` contract is to support the standard `display` function -- see <<displayFunction>>. This, in turn, is used whenever a string <<Interpolation>> expression is used.

\begin{aside}
One of the primary benefits of allowing programmers to define their own implementation of `pPrint` is to enable higher quality display of values. By defining `pPrint` for yourself, you can use application oriented display of your values.
\end{aside}


=== Implementing the `pPrint` Contract
As noted above, the `pPrint` contract is automatically implemented for standard types and for user-introduced types. However, it is quite possible to define one's own implementation. For example, supposing that values of the `tree` type:
[listing]
type tree of t is empty or node(tree of t,t,tree of t)

were intended to be display:
[listing]
{ "alpha" "beta" "gamma" }

instead of the default form:
[listing]
node(node(empty,"alpha",empty),"beta",node(empty,"gamma",empty))

then the following implementation of `pPrint` would ensure that such trees were displayed more conveniently:
[listing]
implementation for all t such that
    pPrint over tree of t where pPrint over t is {
  ppDisp(T) is ppSequence(2,cons of [ppStr("{"),
                                         treeDisplay(T),
                                         ppStr("}")])
} using {
  treeDisplay(empty) is ppSpace
   |  treeDisplay(node(L,Lb,R)) is
        ppSequence(0,cons of [treeDisplay(L),
                              ppDisp(Lb),
                              treeDisplay(R)]);
}

\begin{aside}
Note how the use of `ppDisp` within the definition of `treeDisplay` will ensure that the display of tree labels may also be overridden with user-defined implementations of `pPrint`.
\end{aside}

=== `display` -- display a value as a string
[[displayFunction]]
[listing]
display has type for all s such that
                 (s)=>string where pPrint over s

The `display` function returns a `string` representation of its value.

The `display` function is defined in terms of the `pPrint` contract defined in Program~\vref{ppContractProg}.
\begin{aside}
Although the system attempts to format the result in a way that can be parsed back; this is not guaranteed. In particular, this is not possible for any values that represent programs -- such as functions and procedures. Furthermore, user-defined implementations of `pPrint` may result in non-parseable output.
\end{aside}

== The `formatting` Contract
[[formatContract]]
The `formatting` contract specifies the single `\_format` function which is intended to represent how values should be formatted.

The `formatting` contract itself is defined in Program~\vref{formatContractProg}. The result of a call to `\_format` is a structured `string`.

\begin{program}
[listing]
contract formatting over t is {
  _format has type (t,string)=>pP;
}

.The `formatting` Contract[[formatContractProg]]
\end{program}



\begin{aside}
Normally, like `display`, calls to `\_format` are represented implicitly in string <<Interpolation>> expressions.
\end{aside}
=== Formatting Codes
[[formattingCodes]]
A formatting code is a description of how a numeric or `string` valued expression should be displayed. Formatting codes allow more detailed control of the representation of the format in terms of minimum and maximum widths of output, the number of decimal places to show and the style of representing numbers -- including how negative numbers are displayed and the display of currencies.

A formatting code is introduced with a `:` character immediately after the `\$` form and is terminated by a `;` character. An invalid formatting code is ignored, and treated as though it were part of the quoted string proper.

Each type of value to be formatted may have different formatting codes; reflecting the natural variations in the type. For example formatting integral values may involve ways of managing the display of the sign of the number and formatting `date` values involves ways of show dates and times.

For example, to show a dollar value -- represented as pennies -- in _accounting style_ we can use:
[listing]
"Balance: $Amnt:P999900.00P; remaining"

This format spec displays at least the four least significant digits of the variable `Amnt`. If the value of that variable is greater than 9999 then the leading digits are displayed also -- up to a maximum of eight digits. If the value of `Amnt` is negative then the number is displayed enclosed in parentheses.

For example, if `Amnt` had value -100000, then the value of the expression would be:
[listing]
Balance: (1000.00) remaining

If `Amnt` were 10000:
[listing]
Balance:  1000.00  remaining

\begin{aside}
Note the additional spaces: if the  `P` mode is used for representing sign, a white space character is generated for positive numbers. This facilitate straightforward alignment of columnar reports.
\end{aside}
If `Amnt` had value 45, then the result would be:
[listing]
Balance:  00.45  remaining

The `'0'` in the format will result in leading zeros being printed.
\begin{aside}
If a value cannot be represented in the delimited number of characters then the string:
[listing]
*Error*

is displayed; at least, as much of `*Error*` as is possible in the allocated space.\end{aside}


=== `format` -- format a string for display
[[formatStringFunction]]
[listing]
format has type (string,string)=>string


\begin{aside}
The `format` function for `string` values is normally invoked implicitly within a `string` <<Interpolation>> expression. For example,
[listing]
"--$Msg:C13;--"

is equivalent to the expression:
[listing]
"--"++format(Msg,"C13")++"--"

and has value:
[listing]
"--   freddie   --"

assuming that the value of the `Msg` variable is `"freddie"`.
\end{aside}

The format specification for `string` values is given in the regular expression:
[listing]
`[LCR][0-9]+`

where each control code is defined:
\begin{description}
`L`::
The value is shown left-aligned in the text.

The decimal value immediately after the `L` character is the size of the field.

If the displayed length of the number or string is less than that permitted; then the value is shown left-aligned. If the length of the value is greater than the size of the field then the text is truncated -- i.e., the first N characters of the value are used.

`R`:: The value is shown right-aligned in the text -- if the length of the value is less than the size of the field.

If the length of the value is greater than the size of the field then the text is truncated.

`C`:: The value is shown centered in the field.
\end{description}

\begin{aside}
The `format` function is defined in terms of the `\_format` function and the `formatting` contract -- see Program~\vref{formatContractProg}.
\end{aside}

== Standard String Functions
[[simpleString]]
In addition to certain specific string functions -- such as string concatenation -- the `string` type implements the `comparable` contract which enables `string` values to be compared. The `indexable` contract -- see Program~\vref{sizeableContract} -- is also implemented for `string`s, which means that the normal `[]` notation may be used to access the characters of a string.

=== `isEmpty` -- test for empty string
[[stringEmptyFunction]]
`isEmpty` is part of the standard `sizeable` contract (see Program~\vref{sizeableContract}):
[listing]
isEmpty has type (string)=>boolean

The `isEmpty` function returns true if its argument is the empty string. It's definition is equivalent to:
[listing]
isEmpty(X) is X="";


=== `size` -- size of the string
[[stringSizeFunction]]
`size` is part of the standard `sizeable` contract (see Program~\vref{sizeableContract}):
[listing]
size has type (string)=>integer

The `size` function returns the number of Unicode characters in the `string`. Note that this is not generally the same as the number of bytes in the string.

=== `flattenPP` -- Flatten a Structured String
(((flattenPP@`flattenPP`)))
[listing]
flattenPP has type (pP)=>string;

The `flattenPP` function takes a structured string and `flattens it' into a regular `string`.

\begin{aside}
This function is used by the standard functions `display` and `format` to convert the result of displaying or formatting a value into a `string`.
\end{aside}

=== `<` -- less than
(((<@`<` predicate)))
[listing]
(<) has type (string,string)=>boolean

`(<)` is part of the standard `comparable` contract -- see Program~\vref{comparableContract}.

String comparison is based on a lexicographic comparison: one `string` is less than another if its first character is less than the first character of the second -- irrespective of the actual lengths of the strings. Thus
[listing]
Abbbbbbb < B

because `A` is less than `B`. Characters are compared based on their _code point_ within the Unicode encoding. footnote:[This is the same concept of string ordering as that within Java\tm.]

=== `=<` -- less than or equal
(((=<@`=<` predicate)))
[listing]
(=<) has type (string,string)=>boolean

`(=<)` is part of the standard `comparable` contract -- see Program~\vref{comparableContract}.

The `=<` predicate for `string` values is satisfied if the left argument is less than or equals to the right argument under the lexicographic ordering.

=== `>` -- greater than
(((>@`>` predicate)))
[listing]
(>) has type (string,string)=>boolean

`(>)` is part of the standard `comparable` contract -- see Program~\vref{comparableContract}.
The `>` predicate is satisfied if the left argument is lexicographically greater than the right argument.

=== `>=` -- greater then or equal
(((>=@`>=` predicate)))
[listing]
(>=) has type (string,string)=>boolean

`(>=)` is part of the standard `comparable` contract -- see Program~\vref{comparableContract}.
The `>=` predicate is satisfied if the left argument is lexicographically greater than or equal to the right argument.

=== `\_index` -- Index Codepoint from String
[[indexString]]
`\_index` is part of the standard `indexable` contract -- see Program~\vref{indexableContractDef}.
[listing]
_index has type (string,integer)=>option of integer

The `\_index` function returns a CodePoint from a `string` value at a particular position.

One can use the the normal indexing notation to access CodePoints from a `string` -- as with other kinds of `indexable` types:
[listing]
S[ix]

instead of
[listing]
_index(S,ix)


=== `\_slice` -- Substring
[[sliceString]]
`\_slice` is part of the `sliceable` contract -- see Program~\vref{sliceableContractProg}.
[listing]
_slice(string,integer,integer)=>string

The `\_slice` function extracts a substring from its first argument. The first character of the extracted substring is identified by the second argument; and the end point of the substring is identified by the third argument. An expression of the form:
[listing]
_slice("this is a string",5,7)

returns the substring `"is"` -- corresponding to the two characters located at positions 5 and 6 in the source string.

There is a special notation for this functionality: the slice notation (see <<sliceFunction>>. For example, if the variable `S` is bound to the string `"this is a string"`, then the above expression may be written:
[listing]
S[5:7]


=== `\_splice` -- Replace Substring
[[spliceString]]
`\_splice` is part of the `sliceable` contract -- see Program~\vref{sliceableContractProg}.
[listing]
_splice has type (string,integer,integer,string) => string

The `\_splice` function replaces a substring within its first argument. For example, the expression:
[listing]
_splice("this is a string",5,7,"was")

has, as its value:
[listing]
"this was a string"


Like the `\_slice` notation, there is special syntax for this function -- when used as an action. The action:
[listing]
S[ix:tx] := U

is equivalent to the assignment:
[listing]
S := _splice(S,ix,cx,U)


=== `++` -- string concatenation
[[stringConcatFunction]]
`++` is the standard string concatenation function. It is part of the `concatenate` contract (see Program~\vref{concatenateContractDef})
[listing]
(++) has type (string,string)=>string;


(((string,interpolation)))
Use of the `++` function over strings is implied by the _string interpolation expression_ (see <<StringInterpolation>>). For example, the string expression:
[listing]
"Count = $count, Sum=$sum"

is shorthand for
[listing]
"Count ="++display(count)++", Sum="++display(sum)


=== `explode` -- Explode a string to code points
[[stringExplodeFunction]]
The `explode` function is part of the `explosion` contract.
[listing]
explode has type (string)=>cons[integer];

\begin{aside}
This version of the `explode` function is useful when performing complex operations over `string` values. For example, it can be more efficient to first of all `explode` a `string` before tokenizing the string.
\end{aside}

=== `implode` -- Implode a cons list[code] points to a string
[[stringImplodeFunction]]
The `implode` function is part of the `explosion` contract.
[listing]
implode has type (cons[integer])=>string;

The `implode` function takes a `cons` list of `integer` code points and constructs a `string` value from it.

=== `reverse` -- Reverse the characters in a string
[[stringReverseFunction]]
The `reverse` function is part of the `reversible` contract -- see Program~\vref{reversibleContractDef}.
[listing]
reverse has type (string)=>string


=== `findstring` -- string search
[[findStringFunction]]
`findstring` is used to determine the (next) location of a search token within a `string`.
[listing]
findstring has type (string,string,integer)=>integer;


(((string,search within)))
(((finding substrings)))
The `findstring` function searches a string for an occurrence of another string. The first argument is the string to search, the second is the search token, and the third is the integer offset where to start the search.

For example, the result of the expression:
[listing]
findstring("the lazy dog jumped over the quick brown fox","the",5)

is `25`.

If the search token is not present then `findstring` returns -1;

=== `gensym` -- Generate Unique String
[[gensym]]
(((gensym standard function@`gensym` standard function)))
[listing]
gensym has type (string)=>string

The `gensym` function is used to generate unique strings that have an arbitrarily high probability of being unique.

The generated string has a prefix consisting of the single argument, a middle which is a unique string generated based on a globally unique identifier identifying the current process and a counter.

The result is a string that has a high probability of being unique. It is guaranteed to be unique within the current processor.

=== `spaces` -- Generate a string of spaces
[[spaces]]
(((spaces standard function@`spaces` standard function)))
[listing]
spaces has type (integer)=>string


The `spaces` function generates a `string` containing only the space character -- `'\spce'`. For example, the value of
[listing]
spaces(3)

is the `string`
[listing]
"   "

