= System Access
[[systemFunctions]]

These functions allow the Star application to access the Posix
environment that the application is running in; for example,
`getenv` accesses an environment variable.

== Environment Variables

These functions allow the programmer to access and set environment variables.

[NOTE]
****
In order to use these functions, it is necessary to import the
`star.system` package:

[source,star]
----
import star.system.
----
****


=== `getenv`

The `getenv` function retrieves the value of an environment
variable, as an optional string:

[source,star]
----
getenv:(string) => option[string]
----


If the environment variable is not set, then `.none` is returned.

=== `setenv`

The `setenv` function sets an environment variable:

[source,star]
----
setenv:(string,string)=>().
----

The `setenv` function takes the name of an evironment variable,
and a `string` value, and sets the environment variable to the
new value.

=== `envir()`

The `envir` function returns a list of tuple pairs consisting of
all the environment variables defined.

[source,star]
----
envir:()=>cons[(string,string)].
----

== Process

=== `_exit`

The `_exit` function terminates the @Star{} application with a numeric code:

[source,star]
----
_exit:(integer) => _unreachable_
----

The `_exit` procedure does not return. Instead, it results in the
termination. The argument of `_exit` is used as the value of the
process itself. An exit value of zero implies that the process
terminated successfully.

=== Execute `shell`

The `shell` function executes a sub-process and returns the
integer return code from running the command.

[source,star]
----
shell:(string,cons[string],cons[(string,string)]) => integer raises errorCode
----

The first argument is the file path of the command file to execute;
the second is a list of arguments to the command and the third
argument is the environment variables to pass to the command.

The return value from executing the command is returned by
`shell`. By convention, a return value of zero means that the
command succeeded.

NOTE: The `shell`'ed command is executed to completion _before_
the `shell` call returns. If it is desired to execute a
sub-process concurrently then use the `pipe` function.

=== Pipe function

The `pipe` function is used to execute a shell command in another process while
retaining the ability to interact with it -- via I/O.

== Logging
An application may log output to standard logging facilities using the `logMsg` action procedure.

=== `level` -- type
(((level type@`level` type)))

The `level` type defines a set of logging levels that may be used to indicate the severity of the logged message.
[source,star]
----
public logLevel ::=
    .finest |
    .finer |
    .fine |
    .config |
    .info |
    .warning |
    .severe.
----

The different logging levels have an intended interpretation designed to facilitate users of applications manage the type and quantity of logging flow:

finest:: is used for very fine grained logging, typically insDebugging.
finer:: is used for fine grained logging.
fine:: is used for reporting of internally significant events within an application.
config:: is used to report application configuration events.
info:: is used to report important application events.
warning:: is used to report a recoverable error condition.
severe:: is used to report an unrecoverable error.

[#logMsg]
=== `logMsg` -- log an event
[source,star]
----
public logMsg:all l ~~ loggable[l] |: (l,string)=>().
----
For example, to log an `info` level message one can use
[source,star]
----
logMsg(.info,"You need a tune-up")
----


